### ISSUE TITLE
teardown not working for me

### ISSUE THREAD

**Issue by drhayes** [sintaxi/surge#101]
I'm on OSX 10.10.3, using Node v0.10.26. Running `surge teardown` in a directory in which I just deployed a project doesn't get past the domain prompt.

1. Type `node teardown` into my terminal prompt.
2. Type my email address `drhayes@gmail.com`
3. My token is pre-filled with a lot of asterisks.
4. I type the domain I want to teardown: `like-field`
5. The prompt gets repeated and shows what I already typed.
6. There's no way to get out without <kbd>CTRL+C</kbd>.

![screen shot 2015-05-20 at 4 27 49 pm](https://cloud.githubusercontent.com/assets/8899/7736973/6859a186-ff0d-11e4-8272-797c3cebeea7.png)

No CNAMES or anything fancy, yet. Just trying things out.

**Comment by kennethormandy** [comment]
Try `like-field.surge.sh`, you’ll need to type the full domain. Thanks for the feedback, we should have some improved error messages around this when the domain isn’t valid rather than just re-prompting you.

**Comment by drhayes** [comment]
That did it. :smile_cat: Thanks for the promptness!

**Comment by mauriciogordon847** [comment]
I had also been troubled with the same problem. Happy to find the solution to fix the problem from here. Thanks a lot.

http://essayservices.org

**Comment by kennethormandy** [comment]
I’m going to make this part of the this issue: #23 We’ll try and improve URL validation and feedback afterwards, everywhere in the CLI. Thanks for the feedback!
