### ISSUE TITLE
Remote login and deploy

### ISSUE THREAD

**Issue by callum** [sintaxi/surge#103]
Would it be possible to login remotely using environment variables? I'm looking for a way to integrate surge with CI.

```
$ SURGE_EMAIL=login@email.com SURGE_PASSWORD=***** surge
```

Or even a token-based approach, where first you generate a token with `surge token`, and then:

```
$ SURGE_TOKEN=mytoken surge
```

Any of these variables could be stored securely through a CI provider.

**Comment by kennethormandy** [comment]
Hey! thanks for opening an issue. We’re working on adding `--token` after some discussion in #63. I’m going to close this issue in favour of that, but feel free to add any thoughts or use cases you have there.

Thanks!
