### ISSUE TITLE
Forcing SSL doesn't work

### ISSUE THREAD

**Issue by mphasize** [sintaxi/surge#114]
I am trying to follow these instructions https://surge.sh/help/using-https-by-default to turn on enforcing HTTPS, but the CLI won't accept a domain with a protocol. Whenever I hit enter, it comes back to me with the previous line (prefilled).

```
$ surge --domain https://mytest.com
email: my-email@example.com
token: *****************
project path: /myproject/dist
size: 36 files, 1.6 MB
domain: https://mytest.com
domain: https://mytest.com
domain: https://mytest.com
domain: https://mytest.com
```

surge --version reports 0.13.0

**Comment by kennethormandy** [comment]
Hey, thanks for opening an issue. Sorry for the trouble! This should be fixed now if you update to the latest version with:

```
npm install -g surge
```

I’m going to close this, but definitely let me know if it causes you any more problems.
