### ISSUE TITLE
Would be nice if CLI prompted to save CNAME

### ISSUE THREAD

**Issue by cfjedimaster** [sintaxi/surge#123]
When I surge a site that I'm going to keep around for a bit but never assign a 'real' CNAME, it would be nice if the Surge CLI would prompt to save the random CNAME when done surging. Yeah it wouldn't save me a lot of time, but would be nice.

**Comment by kennethormandy** [comment]
We were thinking of doing a post deploy message, but not necessarily prompts. This could fit well into that. I think you’re right it can be confusing sometimes that the `.surge.sh` subdomain doesn’t stick, but we also wanted to avoiding the command line tool changing the git status buy adding files (also why we avoided any sort of config getting added to the project).

**Comment by cfjedimaster** [comment]
Makes sense.

On Wed, Jul 15, 2015 at 1:52 PM, Kenneth Ormandy <notifications@github.com>
wrote:

> We were thinking of doing a post deploy message, but not necessarily
> prompts. This could fit well into that. I think you’re right it can be
> confusing sometimes that the .surge.sh subdomain doesn’t stick, but we
> also wanted to avoiding the command line tool changing the git status buy
> adding files (also why we avoided any sort of config getting added to the
> project).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sintaxi/surge/issues/123#issuecomment-121710921>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by kennethormandy** [comment]
I’m going to close this issue now. We’ve got a new page about copying over files, when your static site generator or build tool doesn’t support it: https://surge.sh/help/copying-extra-files-into-the-directory-you-publish

Hopefully that helps things a little, as this does still occasionally comes up. Once we add post-publish messages this might show up there too.
