### ISSUE TITLE
Unable to login; continuous password reset

### ISSUE THREAD

**Issue by xopj** [sintaxi/surge#126]
Windows 7
Running from Node.js command prompt

I'm able to get to the password question and go through 3 tries with a correct password then it resends the reset. Website accepts the password and the process repeats.

**Comment by kennethormandy** [comment]
Hey @xopj,

Really sorry for the trouble. We’re trying to take care of this problem but are having troubles reproducing it. In the meantime, some other people have found success using the Git Bash instead of the default included Windows Command Prompt.

I will try and investigate it more, would you mind sharing the version of Node, npm, Surge, and git you are using with me? You should be able to get those with the following command:

```
surge --version
node --version
npm --version
git --version
```

Would you also mind testing for me if you can install other modules globally? Ex. what happens when you try and `npm install -g browserify`? There has been some indication it might be a problem with installing modules globally, not specifically with installing Surge.

**Comment by xopj** [comment]
Surge 0.14.3
node 0.10.22
npm 1.3.14
git 1.9.5

Browserify installed globally fine without any issues. The current test project is just the static hello world page so I couldn't do much in the test project with it, but I have browserfiy working on another project right now.

**Comment by kennethormandy** [comment]
Thanks. Would you also mind sharing how you installed Node? Someone else who had encountered a similar issue had installed it [through Chocolatey](http://chocolatey.org), and while I don’t think that ended up being the culprit, I would like to do my best and recreate the situation.

**Comment by xopj** [comment]
Node was installed via the MSI 64bit installer.

**Comment by kennethormandy** [comment]
When you are logging in, Surge should be writing to a file called `.netrc`. Would you mind sending me the Surge section of that file so we can see if it’s formatted properly?

It should be located in `C:\Users\Your Name\.netrc` and look something like this:

```
machine surge.sh
    login kenneth@surge.sh
    password ab1a1012123abc12345a1ab12345ab12
```

If you don’t mind emailing that to me at [kenneth@surge.sh](mailto:kenneth@surge.sh), it would be really helpful. If the file isn’t there, that’s also helpful. Thanks so much for your patience!

**Comment by xopj** [comment]
Sent, the formatting looks identical.

**Comment by kennethormandy** [comment]
Another case of this, from [our chat](https://surge.sh/help/chat)

> node version: v0.12.7
> npm version: 2.11.3

> Both windows 7 and windows 10 machines are pretty fresh installs, installed from MSDN bootable ISO

> mynameiswarren [3:42 PM]
Then installed NodeJS x64

> Yes, that's what I was initially trying... on Windows 10 I'm seeing a "Node.js command prompt" under apps, both that and the default have the same issue though

> mynameiswarren [3:47 PM]
I have actually just got it to work... but only under my home directory, i.e. c:\Users\warren\surge_test

> mynameiswarren [3:47 PM]
where as p:\projects\surge_test doesn't work

> mynameiswarren [3:47 PM]
even though I have full permissions

> when running "surge" under my user location, it appears to auto-flll the email and token, but on "p" email is initially blank

> kenneth [3:47 PM] 
Oh interesting. `P:\` is another drive you are on?

> mynameiswarren [3:48 PM]
yes, "p" is a local drive partition

This lines up with another instance of this where:

- It wasn’t working while not on `C:\`, also with full permissions.
- It works with Git Bash but not the Node.js or Windows Command Prompt

**Comment by xopj** [comment]
It fails on a c:/repos/my_project directory for me

**Comment by kennethormandy** [comment]
Hey @xopj,

Last week, we released v0.14.4 of Surge, which should fix this problem! You can install or update Surge with:

```sh
npm install --global surge
```

Please let me know how it goes! If you’d like, you can [read more about the update here](https://medium.com/@kennethormandy/257ab847aa0d).

**Comment by xopj** [comment]
Verified it works, thanks so much for resolving this I'll look into giving it a real world test in the near future.

**Comment by tevko** [comment]
I'm currently having this same issue on windows 10 after following the steps above

**Comment by Vishala09** [comment]
Unable to login to surge cli. Gives wrong password error and does not send email to reset as well. Please help!
