### ISSUE TITLE
moniker.js doesn't exist.

### ISSUE THREAD

**Issue by NurdTurd** [sintaxi/surge#128]
`var moniker = require("moniker")`
in /lib/middleware/domain.js should be removed since there is no file in /lib/middleware/ named moniker.js

**Comment by NurdTurd** [comment]
Never mind I'm stupid. It's probably a system wide require(). Sorry for the trouble.

**Comment by kennethormandy** [comment]
Not at all! Thanks for taking a look at the source. :)
You’re right it is requiring a package, however: [weaver/moniker](https://github.com/weaver/moniker)

Feel free to let us know if you have any other questions. Thanks for opening an issue.

**Comment by NurdTurd** [comment]
No problem. I love looking at code :+1:
