### ISSUE TITLE
should be able to add collaborator(s) using `--add <email>` flag

### ISSUE THREAD

**Issue by sintaxi** [sintaxi/surge#13]
The following should deploy the **current working directory** to `http://thurston.surge.sh` and grants Thurston deploy access...

long format...
````
surge \
  --project ./ \
  --domain sonicyouth.com \
  --add thurston@sonicyouth.com
````

short flags...
````
surge -p ./ -d sonicyouth.com --a thurston@sonicyouth.com
````

should also be able to add multiple people...
````
surge . sonicyouth.com --add thurston@sonicyouth.com --add kim@sonicyouth.com
````

shart hand (all arguments after the second should be email)...
````
surge . sonicyouth.com thurston@sonicyouth.com
````

**Comment by crtr0** [comment]
Any update on when it will be possible to add collaborators?

**Comment by sintaxi** [comment]
Working on this now. It's very close to landing.

**Comment by hackygolucky** [comment]
Checking back on an update for this. We're loving using surge for CasadiaJS but I'm pinging @crtr0 to deploy when there's a quick change that needs to happen.

**Comment by sintaxi** [comment]
Just finishing up a new release. We'll have an update by EOD.

**Comment by sintaxi** [comment]
Still coming along. sorry for the delay. working out some of the details.

**Comment by sintaxi** [comment]
this is all done. 

@hackygolucky, @crtr0 has this mechanism worked ok for you??

**Comment by hackygolucky** [comment]
It's golden!
