### ISSUE TITLE
.well-known/keybase.txt not deployed

### ISSUE THREAD

**Issue by orlin** [sintaxi/surge#143]
I'm deploying https://github.com/astrolet/astrolet.co with surge and the `www/.well-known/keybase.txt` is not being served.  Guessing that you filter .hidden directories?

**Comment by kennethormandy** [comment]
Hey, thanks for opening an issue. Yeah, we ignore `.` directories by default. You can override those settings though: https://surge.sh/help/ignoring-files-and-directories

If you add a `.surgeignore` file, and add the following, it should work okay:

```
!.well-known
```

Let me know how that goes!

**Comment by orlin** [comment]
It works fine, thanks for the quick response.  However the documentation is a bit misleading.  It says that `.surgeignore` must be "in the root of your project".  Is that the project repo or the project's compiled public dir that gets deployed?  One would think it's the project repo, because the next sentence says"It works just like a .gitignore file".  If the public dir is a sub-directory of the project dir, it's no longer clear where the file should be and whether the paths should be relative to the www dir or the `.surgeignore` file location.  The question is fine to close as far as I'm concerned, though the help doc could be made clearer.

**Comment by kennethormandy** [comment]
Hey @orlin,

I updated the `.surgeignore` help page, hopefully improved based on your suggestion: https://surge.sh/help/ignoring-files-and-directories

I also added a new page about copying over files into the directory you want to publish: https://surge.sh/help/copying-extra-files-into-the-directory-you-publish

If you have a chance, I’d appreciate your feedback on it. Thanks again for opening this issue.
