### ISSUE TITLE
How do I remove domain/delete site?

### ISSUE THREAD

**Issue by prashcr** [sintaxi/surge#167]
I pushed to a couple of surge.sh subdomains for testing purposes and then realised I won't need them, and then created some new ones.

It feels wasteful to hog so many domains, how can I delete sites that I'm not using anymore?

**Comment by karlfreeman** [comment]
Best thing to do would be to run `surge list`, pick the ones you no longer need and then ["teardown"](https://surge.sh/help/tearing-down-a-project) that project `surge teardown that-project.surge.sh`. Tearing down a project is the equivalent of deleting the project.

**Comment by prashcr** [comment]
Ah, silly me, thanks!

**Comment by ThomLaGreca** [comment]
Would you be able to teardown the following please... Iv used the commands (surge teardown [both]) without any luck...

hurried-crowd.surge.sh
hurried-crowd.surge.sh(hannahwarrencreative.com)

**Comment by sanjay555** [comment]
@karlfreeman   `surge list` gives me `[object object]` list.

**Comment by Kirusshenkin** [comment]
How to delete everything at once?

**Comment by arrahmanbd** [comment]
thanks its worked
