### ISSUE TITLE
Routing with pushState not working

### ISSUE THREAD

**Issue by limzykenneth** [sintaxi/surge#172]
Hi, I'm trying to deploy a single page app built with Backbone.js. I'm using Backbone router with pushState for URL routing and renaming index.html to 200.html so it handles all request.

However, I couldn't get the URL `example.surge.sh/myroute` to work as intended, it always return the 404 page. I hope that's enough details but feel free to ask me for more details.

Is there something I'm doing wrong here?

**Comment by kennethormandy** [comment]
That sounds like you’ve done everything you need to. Are you able to post the actual project URL, and I’ll take a closer look? Thanks for opening an issue.

**Comment by limzykenneth** [comment]
[This](http://sweltering-fear.surge.sh) is the home page and [this](http://sweltering-fear.surge.sh/designing) is one of the route I'm trying to get to. I have a custom 404 page set up as well. Cheers.

**Comment by kennethormandy** [comment]
Hey, I checked and there’s not actually a `200.html` file published to that project. Is the renaming step from `index.html` to `200.html` working for sure?

**Comment by limzykenneth** [comment]
Ah, silly me, I forgot to rename it. I'm still having a bit of a problem but it might just be on my side. I'll pop back if there's still a problem. Thanks a lot!

**Comment by limzykenneth** [comment]
All sorted, thanks again!
