### ISSUE TITLE
Provide way to drop ownership of subdomain

### ISSUE THREAD

**Issue by TrevorSayre** [sintaxi/surge#175]
I can view my subdomains with `surge list`

If I see a subdomain I no longer wish to maintain ownership of, there is no way to drop it via the CLI. 

Something like `surge drop bad-speellingg.surge.sh` should drop ownership of `bad-speellingg.surge.sh` such that `surge list` no longer displays it.

**Comment by kennethormandy** [comment]
Hey, here’s how you can [teardown a project](https://surge.sh/help/tearing-down-a-project). That will take it offline and remove it from your `surge list`. Let us know if that works for you!

**Comment by TrevorSayre** [comment]
Thank you. I guess it wasn't clear that "tear down a published project" included removal of that domain from your ownership. That worked just fine for my need, thank you.
