### ISSUE TITLE
Keep getting 404 Page not found errors

### ISSUE THREAD

**Issue by david-meza** [sintaxi/surge#179]
I've run both the `surge` command and `surge --domain park-jobs.surge.sh` commands and they successfully deploy giving me the following message `Success! Project is published and running at powerful-news.surge.sh`, but when I check the address I get a page not found. What could be the reason for this? I just did it with another of my apps maybe 5 minutes ago and it worked perfectly. I do have a `.surgeignore` file on both projects adding the `bower_components` directory that is being ignored in source control. I do not think this is the issue, though. I also have my cache disabled so I don't think it's a CDN caching issue. Thanks for any help with this issue!

**Comment by david-meza** [comment]
Solved it! This isn't documented but apparently there must be an `index.html` page in your root level of your project path for it to work (similar to gh-pages). Mine was inside the `/app` folder so it wasn't being recognized.

**Comment by kennethormandy** [comment]
Hey, sorry about that. Just to be clear, the project would have been published successfully event without the `index.html` file, so if you went to `park-jobs.surge.sh/app/` it would have shown it even without that change you made.

We have it on our list to improve the 404 page when it’s in the root of the project, to make what’s going on more clear. Thanks for opening an issue!

**Comment by gaearon** [comment]
Was just confused by this, glad I found this thread.

**Comment by mtt87** [comment]
I'm getting this randomly ~ once a week, I'm using `create-react-app` and I've done this `deploy.sh` simple script:
```bash
npm run build &&
mv build/index.html build/200.html &&
surge -p build/ -d https://mlsmerchants.surge.sh
```

I've just tried out of curiosity to rename it back `mv 200.html index.html` but I still get `File not Found`.

We are about to launch our app in the next weeks and I've bought surge plus for the main website, it's a shame if it randomly stops working with no reason ☹️

**Comment by mtt87** [comment]
I'm getting this randomly ~ once a week, I'm using `create-react-app` and I've done this `deploy.sh` simple script:
```bash
npm run build &&
mv build/index.html build/200.html &&
surge -p build/ -d https://mlsmerchants.surge.sh
```

I've just tried out of curiosity to rename it back `mv 200.html index.html` but I still get `File not Found`.

We are about to launch our app in the next weeks and I've bought surge plus for the main website, it's a shame if it randomly stops working with no reason ☹️

**Comment by sintaxi** [comment]
@mtt87 we'll get to the bottom of the issue Im sure. Its just one of those bugs thats only showing up in production so its hard to track down the source the problem. As a workaround you can modify the file by adding a space at the end and I believe it will work.

**Comment by iamsoughtout** [comment]
I have this same problem. I just got introduced to sh. I finished uploading my files and it showed me a message : 
"Success! Project is published and running at etimsoughtout.surge.sh" However, when i visited the site, I met a "page not found" error. I have tried multiple things to fix this to no avail. Kindly advise on what to do.

**Comment by webbdm** [comment]
@iamsoughtout I'm getting this too. Did they ever find a fix?

**Comment by sintaxi** [comment]
"Page not Found" usually means you are missing an `index.html` file in the root of your project. Verify that you deployed the correct directory.

**Comment by webbdm** [comment]
@sintaxi the index is there in the build folder and it's properly linked to the css & js files

**Comment by iamsoughtout** [comment]
@webbdm i never got a solution from them. I sent a mail to a Brock, who works in Surge. He was replying me for a while, then all of a sudden just went AWOL, without helping to solve the problem. @sintaxi, are you the same Brock I was speaking with? I have an index.html file in the root of the project, and I also shared my file directory pathing with Brock which he didnt fault. He requested to see how I was uploading my file and I sent him a snapshot of my NodeJs command line, showing the processes and the final success message. 

@sintaxi if you are the same Brock, I am still waiting for your response, pls.

**Comment by nolastan** [comment]
If you're using `create-react-app`, make sure you're deploying the `build` folder by updating your `project path`. Check out [this tutorial](https://medium.freecodecamp.org/surge-vs-github-pages-deploying-a-create-react-app-project-c0ecbf317089) for deploying `create-react-app` with surge.

**Comment by fouman75** [comment]
If I just follow the tutorial and deploy /build, I get 404 on the css and js file.

The problem seems to be in the way create-react-app (v1.4.0 in my case) links the files in index.html:
```
<link href="/<project_name>/static/css/main.cacbacc7.css" rel="stylesheet">
<script type="text/javascript" src="/<project_name>/static/js/main.5f822674.js"></script>
```

The files on surge.sh are actually directly in the root folder under /static, not under <project_name>/static. If you manually try accessing the files under <app_name>.surge.sh/static/css/..., the files are indeed available.

Within the build folder, I created a <project_name> folder where I moved /static and the app now works on surge.

Not sure what the solution for this could be. Any thoughts? Probably need to change all the links within the react project.

**Comment by sintaxi** [comment]
@iamsoughtout appologies, I had thought I got you the information you needed. The problem you appear to be having is your `index.html` file is named `Index.html`. If you change that and redeploy your index.html file will load by default.

I think I am going to start to display a default index.html file when one isnt present so that people can see the files they have uploaded. Does that make sense to you all?

**Comment by iamsoughtout** [comment]
after changing my file name to index.html, still showing page not found

**Comment by sintaxi** [comment]
@iamsoughtout be sure to redeploy after making the changes. Here is whats showing on your project.

<img width="830" alt="screen shot 2017-09-19 at 10 31 43 pm" src="https://user-images.githubusercontent.com/867/30628307-66d18e00-9d8a-11e7-9c46-1202b38646ff.png">

**Comment by HarryAdney** [comment]
Hi everyone.
I'm completely new to this, so aware that, y'know, PICNIC, but I'm getting the 404 too. 

Steps taken:
========
In the build folder:
Copied index.html to 200.html
ran surge again
Still 404.
In browser, went to <mydomain\..surge.sh/build
Blank page!! No 404.
View source code: shows the 200.html

**Comment by erinfox** [comment]
Happy I found this. Really helped!

**Comment by BellamyRibeiro** [comment]
Hey GUys I need Help!!!! URGENT! =( My page shows : No Page Found! (https://bellamyribeiro.github.io/)

Im sorry im a noob at this! however My file structure is : https://github.com/BellamyRibeiro/BellamyRibeiro.github.io

Any help is appreciated =( Thanks in advance!!!

**Comment by DylanAttal** [comment]
Thank you for the advice to make sure I have an `index.html` file in my root directory. Saved me a headache!

**Comment by IgorCopa** [comment]
> Solved it! This isn't documented but apparently there must be an `index.html` page in your root level of your project path for it to work (similar to gh-pages). Mine was inside the `/app` folder so it wasn't being recognized.

Thank you for helping me.

**Comment by rahulvyas** [comment]
I am getting same issue I get success when uploading a flutter web build folder. I already have index.html page on root. Still I'am getting 404 error. How do I trace the issue ?

**Comment by sintaxi** [comment]
@rahulvyas its difficult to help you with the limited information you have provided. In most cases when people report this issue they simply deployed the wrong directory. You can visit `/auto.appcache` to see the published files. Please consider opening a new issue (so others don't get emailed) with detailed information (so I can help) if you can't resolve the problem yourself.

**Comment by jessamyn27** [comment]
please add the instructions in "getting started" doc on surge.sh that your root file MUST be called "index.html" I was naming mine app.html and it took me days to figure out that this was the issue, delaying my coding challenge for a hiring process! Other than that y'all are awesome. Might be nice to have a "common issues" or such easily accessed for noobs like me :)

**Comment by sunshinescience** [comment]
Thanks so much, having the index file in the root directory got it to work!
