### ISSUE TITLE
is domain limited?

### ISSUE THREAD

**Issue by calidion** [sintaxi/surge#180]
i uploaded more than one sites seems new domain not working properly.

**Comment by calidion** [comment]
seems there is a gap before publish succeeded.

**Comment by RodrigoHahn** [comment]
Probably gotta wait for DNS propagation to occur. From my experience, it
doesn't take long.

Rodrigo Machado Hahn

**Comment by kennethormandy** [comment]
As @RodrigoHahn mentioned, if it’s a [new custom domain](https://surge.sh/help/adding-a-custom-domain) you’ve just switched over to Surge, it might take some time to propigate. But if it’s something you’ve published before, it should be propigated once you see “Published was published successfully” in the CLI.

**Comment by calidion** [comment]
@kennethormandy 

I have CNAME file with more than one domain.

it seems other domains will be ignored by surge.sh?

if I have the three domains want to be bound into the same server.

CNAME file like:

```
www.aaa.com
www.bbb.com
www.ccc.com

```

now it seems only work with www.aaa.com.

**Comment by kennethormandy** [comment]
Hey, [you can read more about that in this article](https://surge.sh/help/adding-multiple-custom-domains).

We are considering making it wirk this way in the future, but in the meantime, the CNAME file is only a single-line file. There is another issue for that open still if you feel like commenting there too. Thanks for opening an issue!

**Comment by calidion** [comment]
@kennethormandy  thanks.
