### ISSUE TITLE
`surge teardown` not working

### ISSUE THREAD

**Issue by juanmnl** [sintaxi/surge#191]
Hello, i'm having problems with the teardown command.  

1. I created a project named `xxx-yyy/` and added `surge --domain mydomain.com`  
2. Then i added a second domain with the www `surge --domain www.mydomain.com`  
3. I changed the project name to `xxx/` //maybe this is generating a problem :/  
4. I want my `mydomain.com` to be redirected to `www.mydomain.com` so i tried to remove that one `surge teardown mydomain.com` as there were two versions of the site on the CDN.  
5. Received an email with teardown confirmation. Good.  
6. Launch `surge list` and both appear again `mydomain.com www.mydomain.com`  
7. Removed both projects with `surge teardown` and received the corresponding emails.  
8. Test url's on the browser. 404 - Good, projects were taken down.  
9. Went to `xxx/` `surge --domain www.mydomain.com` and uploaded. Everything good.  
10. Make changes to the project.  
11. Launch `surge`, deploying message: `domain: mydomain.com`  
12. Launch `surge list` again and both appear again `mydomain.com www.mydomain.com` 

 

Haven't done anything else. What should i do?

Thanks for your help. :smile:

**Comment by kennethormandy** [comment]
Just to clarify, you removed both projects, and then only published to the one without the `www`, correct? That should automatically setup a redirect from the `www` version to the root version: https://surge.sh/help/redirecting-www-to-root-automatically

If that’s not the case, and you’re able to share the actual domain with us, we can take a closer look. If you don’t it public yet, feel free to [join our chat](https://surge.sh/help/chat) and direct message it to me.

**Comment by juanmnl** [comment]
Thanks for replying so quickly @kennethormandy :)
That's correct, removed both projects, then added only `www.mydomain.com`.  
The problem is when launching the `surge` command it goes back to deploying to `mydomain.com` even after removing both and receiving confirmation of teardown and `surge list` shows both domains, as if there were never gone.  
The domain is [www.juanmnl.com](http://www.juanmnl.com)

I'll try the chat later today.  
Thanks for your help!

**Comment by danreeves** [comment]
Hi @juanmnl, do you have a CNAME file in your project?

**Comment by juanmnl** [comment]
Hi @danreeves, Oh man! I feel really bad and dumb for opening this issue right now!
Yes, i have one and forgot completely about it. Changed and fixed.

Appreciate your help and quick responses!

<3
