### ISSUE TITLE
Routing with react-router

### ISSUE THREAD

**Issue by debopamsengupta** [sintaxi/surge#195]
Hi, I'm trying to deploy a React app to surge.sh

I have 3 routes using `react-router`:
- `/` which opens the Main Component
- `/about` which should open another react component
- `*` which goes to a custom React 404 component

I observe:
- `my-domain.surge.sh` opens the Main Component
- `my-domain.surge.sh/about` opens the surge 404 page
- `my-domain.surge.sh/index` opens my custom 404 React Component

Any suggestions ?

**Comment by danreeves** [comment]
Make sure you're using the `200.html` and not `index.html`

In the [docs](https://surge.sh/help/adding-a-200-page-for-client-side-routing)

**Comment by debopamsengupta** [comment]
@danreeves 
Thanks a lot, it works :)
