### ISSUE TITLE
http/https support for free?

### ISSUE THREAD

**Issue by calidion** [sintaxi/surge#196]
charge by traffic?

**Comment by JimFung** [comment]
From their site, [surge.sh](url) 

> All projects published on Surge receive free, basic SSL support; if your project is http://my-project.surge.sh then https://my-project.surge.sh will also work.

**Comment by jasonkuhrt** [comment]
At least for me this seemingly recently stopped working:

```
❯ curl -vs --insecure https://jasonkuhrt.com/resume.pdf
*   Trying 138.197.235.123...
* TCP_NODELAY set
* Connected to jasonkuhrt.com (138.197.235.123) port 443 (#0)
* WARNING: disabling hostname validation also disables SNI.
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.surge.sh
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> GET /resume.pdf HTTP/1.1
> Host: jasonkuhrt.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: SurgeCDN/1.1.0
< Date: Mon, 25 Sep 2017 16:58:16 GMT
< Connection: close
< Content-Length: 0
<
* Closing connection 0
```

**Comment by Almusamim** [comment]
I'm getting **connection is not secure** message with the free SSL offered with surge!

**Comment by sintaxi** [comment]
@Almusamim please send over more info so we can look into it.

**Comment by Almusamim** [comment]
@sintaxi what info should I provide u with? :)

You can check the website: https://goo.gl/LzfZNj
Thank you

**Comment by derit** [comment]
solution for this problem using **Cloudflare** and get free ssl
