### ISSUE TITLE
200.html and 400.html do nothing on routes with a one-character length first segment /a/, /b/, /c/

### ISSUE THREAD

**Issue by divmgl** [sintaxi/surge#200]
I have a `200.html` and a `400.html` file present in my Surge project and they do absolutely nothing if the first segment has a length of one character. I was able to confirm that this happens to all routes that are one character long.

Works: 

`http://letusknow.io/` 
`http://letusknow.io/ab`
`http://letusknow.io/abc`
`http://letusknow.io/randompagethatdefinitelydoesnotexist`

Does not work:

`http://letusknow.io/c/letusknow.io`
`http://letusknow.io/c/`
`http://letusknow.io/c/bluenrgy.com`

I can change my routes around in the meantime, but this is pretty problematic. Thanks.

**Comment by Abdubek** [comment]
how did you decide?
