### ISSUE TITLE
Unable to push new or existing projects to Surge's CDN

### ISSUE THREAD

**Issue by david-meza** [sintaxi/surge#201]
First of all, thank you for offering this service.

The issue I'm having is when I push a project to the CDN, it doesn't reflect the updated changes. For example, I've tried the following:

![2016-04-06_13-35-07](https://cloud.githubusercontent.com/assets/11840636/14329577/f9d79b78-fc09-11e5-8c41-72b8be605637.png)

But when I visit the project's URL, it is still showing the same build from last week.

**Comment by jdcauley** [comment]
Second this, new project landing on the not found page.

**Comment by hellmer** [comment]
+1 here!!

**Comment by sintaxi** [comment]
Thanks for reporting. looking into it.

**Comment by david-meza** [comment]
Thank you. This seems to have been fixed yesterday evening. I'll go ahead and close this issue. It would be nice to know what happened, if possible. :)

**Comment by sintaxi** [comment]
Hey @david-meza. Early in the morning A code release went out which essentially caused publishings to write to `/dev/null`. This did not alter the live website as intended. The problem was found and addressed at around noon. Apologies for any troubles this may have caused.

**Comment by parris** [comment]
This seems to be occurring right now: The surge CLI reports that everything is fine and that I should see something here: http://threejs-experiments.surge.sh/

**Comment by parris** [comment]
Woops, nvm! All is working fine!

**Comment by rtharasyn** [comment]
Hello @david-meza - Thank you for the update and providing the service (Huge fan). This seems to be an issue for me post the fix, however:

<img width="407" alt="screenshot 2017-04-06 11 14 56" src="https://cloud.githubusercontent.com/assets/3958643/24769270/c0b057ce-1aba-11e7-90b1-ef6e79947378.png">

I receive confirmation, but it is not reflected on the live site.
