### ISSUE TITLE
Surge lists projects which are not mine

### ISSUE THREAD

**Issue by jiayihu** [sintaxi/surge#206]
When I run `surge list` I get a list of domains which I never used and known about.
For example this is the list I get, excluded my own domain names:

```
*.myevent.sintaxi.com
*.angularattack.io
*.kenneth-event.kennethormandy.com
*.super.sintaxi.com
```

Also I cannot `teardown` any of them. Is it a security issue?

**Comment by notcoling** [comment]
I'm having this issue as well.

**Comment by wires** [comment]
I'm getting "Empty - No Projects found.", while I just ran a deploy which resulted in "Success! project is published and running" message...

**Comment by sintaxi** [comment]
resolved.
