### ISSUE TITLE
Surge SSL configuration fails Qualys tests.

### ISSUE THREAD

**Issue by nbering** [sintaxi/surge#216]
Sites hosted on Surge fail the Qualys SSL Labs tests because of a vulnerability in OpenSSL. Patching server software that depends on OpenSSL and changing a few configuration options should fix the vulnerability.

https://www.ssllabs.com/ssltest/analyze.html?d=surge.sh

**Comment by sintaxi** [comment]
Thanks for reporting this. This must be a regression from when we were defending against recent DDOS attacks. Will fix this ASAP.

**Comment by sintaxi** [comment]
Ok. This is resolved. A+ now. Thanks again for reporting. 👍 

![screen shot 2016-06-21 at 9 39 48 am](https://cloud.githubusercontent.com/assets/867/16238185/66250156-3794-11e6-8bfa-4d739899999c.png)

**Comment by nbering** [comment]
No problem. Thanks for the quick fix!
