### ISSUE TITLE
Make project URL clickable

### ISSUE THREAD

**Issue by sotojuan** [sintaxi/surge#218]
Changing

> Project is published and running at project.surge.sh

To

> Project is published and running at https://project.surge.sh

Will make the URL clickable in terminals like iTerm 2.

Willing to do a PR for this!

**Comment by kennethormandy** [comment]
Thanks for opening an issue! I think this was done intentionally, but I can’t remember the specifics of why. It wouldn’t be possible to assume it’s `https` for one thing. The URLs are Command+Click-able in iTerm 2 already, does the latest version of iTerm 2 allow clicking without command if `http://` is in front of the URL?

**Comment by sotojuan** [comment]
It can be `http`, and no in my iTerm they're not clickable :sad:

**Comment by sintaxi** [comment]
This is a good idea.

@sotojuan: holding `cmd` on mac will make the url clickable on iTerm.
