### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by Kiefna** [sintaxi/surge#222]
For the last couple of days, surge hasn't worked for me. Whenever I use it, it works fine, no errors. But when I go to the site, I get Page Not Found.
![screen shot 2016-08-09 at 12 24 22 pm](https://cloud.githubusercontent.com/assets/9469079/17530488/9fd1f13e-5e2c-11e6-9817-13f07d29f631.png)
What could this be? Could it be my side?
P.S. I'm the one scrambling :P

**Comment by christoga** [comment]
Can you please show us your project directory?

**Comment by Kiefna** [comment]
Haha, I solved it, it was really stupid. index.html was capitalized, which kept surge from recognizing it. Figured it out pretty quick so I closed the issue.

**Comment by christoga** [comment]
Alright then :)
