### ISSUE TITLE
Allow Page Caching

### ISSUE THREAD

**Issue by ankitjain28may** [sintaxi/surge#226]

**Comment by sintaxi** [comment]
I can only presume you are requesting a different caching strategy then surge currently gives you however I'd like to talk you off this ledge. As it stands surge provides a caching algorithm that ensures the same file is never distributed to the same client more than once per year as well as never displays a stale file, EVER.

If you are looking for a more aggressive caching strategy we strongly suggest using an approach that does not have a dependency on a persistent network connection. This can be done with either a service worker or in some (but more limited) circumstances app cache manifest could work for you.

**Comment by ankitjain28may** [comment]
Exactly!

**Comment by kennethormandy** [comment]
Just for future reference if anyone stumbles across this:

- You can read more about [Surge’s caching strategy in this article](https://surge.sh/help/using-lucid-caching-automatically).
- You can read more about the app cache circumstances @sintaxi mentioned in this article I wrote for David Walsh: [Don’t Wait for ServiceWorker: Adding Offline Support with One-Line](https://davidwalsh.name/dont-wait-serviceworker-adding-offline-support-oneline) (Surge builds your `appcache` file automatically as a fallback, which hopefully buys you more time to focus on ServiceWorker instead!)

**Comment by ankitjain28may** [comment]
Ok
