### ISSUE TITLE
Domain verification bug

### ISSUE THREAD

**Issue by ili-codes** [sintaxi/surge#234]
I am using Surge to host my blog on a subdomain, `blog.iliyan.me`. I have tried to use a CNAME and have added the `na-west1.surge.sh` server to my DNS settings. However, I am getting an error:
`Aborted - you do not have permission to publish to blog.iliyan.me`.  Any reason why this is happening? The DNS settings haven't been changed in 5 hours. I've changed to another static site host for the time being, but would really like to use Surge as the CSS isn't working on this other host.

**Comment by mstijak** [comment]
@ili-codes Sorry, to bother you on an old thread. I'm seeing the same issue. Were you able to solve this problem?

**Comment by nsarafa** [comment]
Try logging out with `surge logout` and logging back in with `surge login`

**Comment by DanHoelck** [comment]
That did the trick!
