### ISSUE TITLE
Page Not Found error

### ISSUE THREAD

**Issue by askrajatkaushal** [sintaxi/surge#236]
Hello Sir / Ma'am,

I just redeployed a project on "d3-charts.surge.sh" which is now giving me Page not found error. Earlier it was working very fine, but after deployment, its not working.

Please look through the issue & help me out by fixing it. I've also tried to deploy the same project on "assign-graphs.surge.sh" & "ass-graphs.surge.sh" just to check if fresh deployment helps. But everywhere same error is being thrown.

Thanks in advance.

**Comment by sintaxi** [comment]
You are seeing that because you dont have any of the follwing files in your project: `index.html`, `200.html`, or `404.html`. You do have an https://d3-charts.surge.sh/test.html file though. Is that what you are expecting to see?

**Comment by askrajatkaushal** [comment]
Ya, thanks sintaxi. I re-uploaded the whole project this time & its working very fine.
Thanks once again.

**Comment by sintaxi** [comment]
glad your unstuck. happy to help :)
