### ISSUE TITLE
Cannot publish to aquila-js.surge.sh

### ISSUE THREAD

**Issue by harinair** [sintaxi/surge#244]
Cannot publish to aquila-js.surge.sh. I used to publish to this domain all the time.

    Surge - surge.sh

              email: hari.gangadharan@pearson.com
              token: *****************
       project path: /Users/ugangha/Sandbox/Pearson/Cite/aquila-js-demo/dist/
               size: 25 files, 3.0 MB
             domain: aquila-js.surge.sh

    Aborted - you do not have permission to publish to aquila-js.surge.sh

**Comment by sintaxi** [comment]
All I can really tell you is that's not the account on file that has access to the domain. So things appear to be operating correctly.

**Comment by harinair** [comment]
@sintaxi can you tell me the few char of the email that holds access? It must be one of my colleagues. I am the one who created this.

**Comment by sintaxi** [comment]
If you look in your email inbox you should see a "Welcome to Surge!" email.

**Comment by nsarafa** [comment]
Try logging out with `surge logout` and logging back in with `surge login`

**Comment by rohyadav** [comment]
I'm having this issue. And i tried to logout and login but doesn't work for me can you please anyone help me out this.
before it was different login id that time worked but when i upload in different domain that got error.
but for now is there anyway to short it out this.

surge --domain imrohit.in

Surge - surge.sh

          email: rohityadav.techie@gmail.com
          token: *****************
   project path: C:\workspaceArea\imrohit\
           size: 13 files, 64.6 KB
         domain: imrohit.in

Aborted - you do not have permission to publish to imrohit.in

**Comment by sintaxi** [comment]
@rohyadav we have a different account on file for that domain. I have emailed the email account we have on file for you.
