### ISSUE TITLE
teardown isn't working properly

### ISSUE THREAD

**Issue by glaksmono** [sintaxi/surge#246]
```
➜  moka-backoffice git:(master) surge list

    Surge - surge.sh

              email: grady@mokapos.com
              token: *****************

      backoffice-dev.mokapos.com,backoffice.mokapos.com

➜  moka-backoffice git:(master) surge teardown "backoffice-dev.mokapos.com,backoffice.mokapos.com"

    Surge - surge.sh

              email: grady@mokapos.com
              token: *****************
             domain: backoffice-dev.mokapos.com,backoffice.mokapos.com

    Aborted - unable to remove backoffice-dev.mokapos.com
```

i.e. by accident we previously added "backoffice-dev.mokapos.com,backoffice.mokapos.com"

Thoughts on how to tear this down? Or what to do here?

**Comment by sintaxi** [comment]
Removed it for you. you should no longer see it in your list of projects.

**Comment by cdunlap** [comment]
So is the fix to have you manually remove a website @sintaxi? I just did it with one of mine and experienced the same problem: site still exist and can't remove it twice. There is another open issue with the same problem: #286 might be some others.

Is there a plan to fix this? Or is there a reason you want to keep sites around after teardown?

**Comment by rainstormza** [comment]
@sintaxi my site still public after teardown.
site : sansiri-survey-demo.surge.sh

I tried surge list and it doesn't have my site in list.

**Comment by jblacklock** [comment]
I'm also having trouble tearing down jesseblacklock.com
I got the following error "Aborted - unable to remove jesseblacklock.com"

I tried "surge teardown jesseblacklock.com"
