### ISSUE TITLE
Keep releases page updated

### ISSUE THREAD

**Issue by RyanZim** [sintaxi/surge#256]
https://github.com/sintaxi/surge/releases doesn't have any release/changelog entries for versions after v0.17.6. Could this please be kept updated? Having a changelog helps me when I need to update my `devDependencies`.

**Comment by sintaxi** [comment]
Good timing. Just released `v0.19.0`. https://github.com/sintaxi/surge/releases/tag/v0.19.0

**Comment by RyanZim** [comment]
Hey, thanks for the quick response @sintaxi. Long live surge.sh!
