### ISSUE TITLE
pdf files return 404 

### ISSUE THREAD

**Issue by tomkp** [sintaxi/surge#257]
All pdf files uploaded with surge are returning 404 errors. 

I've uploaded a pdf, txt and a docx file to the following domain:

http://smoggy-knife.surge.sh/

The txt and docx are fine, but the pdf gives me a 404.

**Comment by sintaxi** [comment]
We recently had an astronomical amount of abuse on surge from people publishing hundreds of GB of copy written PDFs. The results of which was a flood of DMCA complaints. If you have a pdf that you need to publish on surge we can whitelist your domain. You will just need to send us a link to your project.

**Comment by rhythmus** [comment]
So sad to learn Surge.sh got targeted by abusers! That’s why we can’t have nice things…

I came here after googling "surge.sh pdf". It puzzled me why the pdfs in my site’s source dir, deployed using the `$ surge` CLI, didn’t get served, as was previously the (expected) case. _No warnings, no logs in the CLI; everything seemed okay, the CDN propagation and all._ Requests for pdfs just returned 404s. So I looked into `.surgeignore`, and wondered whether the default behavior get changed. Apparently, so it did…

**PDFs are very important** to me — I’d even claim they’re an integral part of the Web; still the better option to `@media print`. I regularly publish nicely styled, **printable pdfs alongside my html, for my readers’s convenience**. I also prefer lightweight pdfs as the **format of choice** when it comes to delivering **presentations/powerpoints**. (As a matter of fact, last week I needed an online slide deck for a lecture and was lost at why I couldn’t use Surge.sh any longer.) Needless to say, in all such use cases it is obvious the publisher of the pdf is also its copyright holder.

I find it a shame the **delivery format (pdf) is the victim** of copyright infringement. **Abusers will always find other ways**: they could wrap pirated content in `.zip`, `.rar`, multipage `.tiff`, `.ps` files, and what have you — even in html itself, in base64 encoded URIs or whatever. tl;dr: you cannot ban delivery formats to mitigate file sharing abuse. There should be other means.

Don’t get me wrong here: I love Surge, I do feel your torment with DMCA pesterings, and I totally understand why you decided simply banning pdfs in batch was the fastest solution to what must have been a disenchanting woe. But myy I suggest an alternative approach?

Maybe you could **allow PDFs for sites** hosted on Surge, but **with a custom domain**, i.e. those with a `CNAME` file in their source, pointing to a domain owned by someone else (the publisher) than you guys. After all, **legally, it is the domain owner (as on WHOIS record) who is liable** for press offenses and copyright infringements, not the hosting provider. Also, the automated DMCA take-down requests would first go to the spammers/abusers/piraters. Who’d have to buy a domain first, setup the DNS records, before they could abuse the free tier of Surge hosting — I guess they’d move on very quickly… 

Sorry for my ramblings. As I said, **I love Surge, but am just desperate about hosting my pdfs.** I hope you can work out a solution.

Meanwhile, please whitelist my domain, which is `dodecaglotta.com`.

Thanks a lot!

**Comment by sintaxi** [comment]
@rhythmus your account has been whitelisted.

**Comment by SiamKreative** [comment]
@sintaxi Could you please whitelist siamkreative.com? I temporarily changed the link to my resume.

**Comment by karel-brinda** [comment]
@sintaxi Could you whitelist tp-zpevnik.surge.sh, please?

**Comment by killerkiara** [comment]
Hi @sintaxi and thanks for the explanations :) I needed to update my CV on my website and suddenly i could not figure out why it would return me a 404. Could you please whitelist my domain as well? It is `chiara.codes`. Thanks a lot!

**Comment by eigenmannmartin** [comment]
Hi @sintaxi yould you please whitelist eigenmannmartin.ch/ as well? Thanks a lot!

**Comment by mike1808** [comment]
@sintaxi I hope you can whitelist my domain mmanukyan.io

**Comment by vitordino** [comment]
@sintaxi i need mine too vitordino.surge.sh

**Comment by bonzobavaria** [comment]
@sintaxi I need my site whitelisted as well. kevinwaddle.com. A little explanation instead of a flat 404 would have been helpful. That was a major wtf moment.

**Comment by proxyusertryingsurge** [comment]
LOL, how many people share such big file(PDF) on Surge(free service)? Don't be greedy, pay what they deserve or compress your PDF to something else(zip,tar,7z,rar,whatever).

**Comment by proxyusertryingsurge** [comment]
@sintaxi How about adding "PDF upload allowed" to Surge+ monthly plan?

**Comment by JesseSoldat** [comment]
@sintaxi Could you whitelist 
https://jesse-soldat.surge.sh

**Comment by juandjara** [comment]
Hello @sintaxi 

Could you pls whitelist [](https://fuken.xyz/CV-juandjara.pdf) ??
That's my resume on my personal webpage

**Comment by paulcpederson** [comment]
@sintaxi when you get a moment, could you also whitelist paulcpederson.com ? Storing my resume in pdf format on there. Also, thanks for surge! Really amazing project...

**Comment by AndreaCensi** [comment]
@sintaxi Could you whitelist http://robot-design.org/ ?

(p.s. this policy really needs to be in the documentation)

**Comment by gaelmaiano** [comment]
Hi @sintaxi 
Could you whitelist http://gael.maiano.fr ?
The pdf is my cv. 
Thanks

**Comment by RynoRn** [comment]
Hi,

Could you please whitelist my domain for 2 very small PDF files please?

**Domain:**
http://pickies.hu

**Files:**
http://pickies.hu/docs/Pickies_nyeremenyjatek_szabalyzat.pdf
http://pickies.hu/docs/Pickies_adatkezelesi_tajekoztato.pdf

Thanks a lot!

**Comment by EliotSlevin** [comment]
Hi @sintaxi 

Could you please whitelist simulating-psychedelic-therapy.surge.sh, and barnett.surge.sh? My friend and I are using surge to host our thesis's, and we need to load two small PDF files. 

Thanks heaps :)

**Comment by nkandrewz** [comment]
Could you please whitelist http://decalscentral.com ?

**Comment by remarks** [comment]
@sintaxi could you please whitelist http://markpinero.com? Thank you!

**Comment by serkansokmen** [comment]
@sintaxi could you please whitelist [birbucuk.org](http://birbucuk.org)?
Thanks a lot!

**Comment by kevinliu743** [comment]
@sintaxi could you please whitelist cs70.kevinmliu.com? Thanks! I'm posting notes for students

**Comment by axbwh** [comment]
@sintaxi Hi, I would really appreciate it if you could white list dww.surge.sh, got a few pdf infographics that need to be published on the site. Cheers.

**Comment by sureshbala** [comment]
@sintaxi Please whitelist the website https://universaltechnoschool.com/
This is the website of a school and they would like to distribute School Brochure and Application Form

**Comment by wesleyllewis** [comment]
@sintaxi Could you please whitelist www.wesleylewis.us? Trying to host my CV. Thanks in advance!

**Comment by jasonkuhrt** [comment]
I got burnt by this silently, I guess my resume has been 404 for a few months now. Can you please whitelist http://jasonkuhrt.com. Thanks!

**Comment by joshwilcken** [comment]
@sintaxi please whitelist http://joshwilcken-portfolio.surge.sh/  I am attempting to whitelist my portfolio site.

**Comment by cotyembry** [comment]
@sintaxi can you please whitelist http://http://sovereignchickamaugacherokee.org/ I am needing to keep an application for hosted and available for the website. Thank you!

**Comment by rosendin** [comment]
@sintaxi can you please whitelist [](http://polyledger.com/) please I would like to share a pdf.

**Comment by cotyembry** [comment]
The way I worked around this issue while waiting for my domain to be whitelisted was to: #1 use github, #2 use an iframe in my site. I chose to embed an iframe in my page to make the domain/url to the user stay my domain name, then set the src of the iframe to be what the url is for the resource on github.com.  To get the url, navigate to the file on github.com after logging and selecting your git project.
Once in the git project, navigate to the file and you click `view raw`. Copy that url. The issue is, the raw view of the file isn't allow to be `executed` so the browser will just download the file. I.e. the raw url of a resource would look like:
    `https://raw.githubusercontent.com/yourGITUsername/gitProjectName/master/asset/application_final.pdf`

A trick, however, is to change the url to be the following instead:

    `https://rawgit.com/yourGITUsername/gitProjectName/master/assets/application_final.pdf`

to allow the browser to correctly use the file type.

I hope this helps

**Comment by sh4hidkh4n** [comment]
could you please whitelist my domain 
http://resume.shahidkamal.surge.sh

**Comment by plugnburn** [comment]
Please whitelist nihilcoin.surge.sh, the only PDF that needs to be published there is our group's manifesto.

**Comment by micahjz** [comment]
@sintaxi Hi, can you please whitelist my domain at www.micahzirn.com. I would like to include my résumé. Thanks!

**Comment by organnoise** [comment]
Hi could you please whitelist ```danielmcn.com```?

Some of my images also won't upload for some reason, are there rules about certain images being uploaded too?

**Comment by andrewjford** [comment]
Hi, could you please whitelist [andrewford.net](andrewford.net)? I have a pdf resume on there, thanks!

**Comment by justinkan9** [comment]
I like many others, have a resume pdf file :) would love to get it whitelisted:

justinkang.surge.sh

**Comment by EliotSlevin** [comment]
I hope it's becoming apparent we need a more sustainable pdf system than
requesting to be on a whitelist - how about a limit to the amount of pdfs
you can upload on a free plan?

**Comment by winstonlan** [comment]
Could you whitelist my domain! winstonlan.me

**Comment by woHangOnAMinute** [comment]
us too!!!

**Comment by dmiotti** [comment]
Same here, could you white liste use:
cocotte-app.com

**Comment by ran-research-lab** [comment]
Could you pls whitelist 3033.surge.sh. I use it for my progeamming course.
Thanks

**Comment by aholson** [comment]
Hi could you whitelist audreyhsuolson.com? Trying to upload a PDF of my resume.

Thanks in advance!

**Comment by sintaxi** [comment]
Hey folks, we're working on a better long term solution for this problem as suggested by @EliotSlevin. until then DM you surge **email address** to [@surge_sh](https://twitter.com/surge_sh) to get whitelisted.

**Comment by aholson** [comment]
@surge_sh aholson@ucsd.edu

**Comment by justinkan9** [comment]
@sintaxi 

Hey, I don't have twitter, but hope you see this to whitelist me 👍 

justinkan9@yahoo.com

**Comment by lmflatt** [comment]
Hey @sintaxi 
It seems like this is the place to get whitelisted for pdfs. Would you be able to add anthonybernarducci.surge.sh ? It's a site for a friend, and he just has a few scholarly publications to show off. My email is lee.m.flatt@gmail.com

**Comment by Chisnits** [comment]
DM'd on twitter but really trying to get whitelisted ASAP. my url is chasederr.surge.sh. my email is chasederr@gmail.com. Please let me know if anything can be done. @sintaxi

**Comment by mqklin** [comment]
@sintaxi DM'd on twitter as well, but no response. Please, whitelist [zerion.io](zerion.io) and [dev.zerion.io](dev.zerion.io). Thank you.

**Comment by sintaxi** [comment]
OK. I think you all have been added now.

**Comment by mqklin** [comment]
Thanks a lot!

**Comment by jasonkuhrt** [comment]
@sintaxi Not for me:

```
❯ curl -vs --insecure https://jasonkuhrt.com/resume.pdf
*   Trying 138.197.235.123...
* TCP_NODELAY set
* Connected to jasonkuhrt.com (138.197.235.123) port 443 (#0)
* WARNING: disabling hostname validation also disables SNI.
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.surge.sh
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> GET /resume.pdf HTTP/1.1
> Host: jasonkuhrt.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: SurgeCDN/1.1.0
< Date: Mon, 25 Sep 2017 16:58:16 GMT
< Connection: close
< Content-Length: 0
<
* Closing connection 0
```

**Comment by edwinbsmith** [comment]
Can I get my domain, http://edwinsmith.org/, whitelisted? Thanks!

**Comment by nwright872** [comment]
@sintaxi Sent you an email, but would you mind whitelisting mine?

http://nick-wright-lafleur.surge.sh/

Much appreciated,

**Comment by eddycaldas** [comment]
@sintaxi 
 would you whitelist my site please:
https://eddycaldas.surge.sh/
Thank you much @sintaxi

**Comment by ntucakovic** [comment]
So sad for abusing such a great tool :(

I've spent hours debugging what might be happening with PDF, thought it was React route bug, never realized that it might be due to host issues... Can you please document it somewhere?

Also, if you can whitelist domains https://ntucakovic.surge.sh & www.ntmedia.me ?
I have cloudflare behind ntmedia.me, so even less bandwidth will be spent for downloading that PDF.

Thank you!

**Comment by oddmouse** [comment]
@sintaxi Would you mind adding [lindy.co](https://lindy.co) to the PDF whitelist as well? Thank you!

**Comment by nettinero** [comment]
@sintaxi Hey if you don't mind adding abbvie.surge.sh to the PDF whitelist also it would be great! Thank you!

**Comment by jessehattabaugh** [comment]
@sintaxi please add consciousfreedom.net to the PDF whitelist

**Comment by oujii** [comment]
I'm sorry to hear about the abuse. That sucks. I would really appreciate if my domain could be whitelisted.
carlwaerner.com

Thanks so much.

**Comment by jessehattabaugh** [comment]
FYI Firebase offers free static file hosting and they allow PDFs https://firebase.google.com/docs/hosting/

**Comment by HaoZeke** [comment]
Hi @sintaxi, could you whitelist zenyoda.surge.sh ?

I use it to show-off a pandoc based presentation system...

**Comment by iamrkcheers** [comment]
Could you please whitelist the following url as well ..
'fortificationbeta.surge.sh'
We're using it for demonstrating this soon-to-be-build application of ours.

**Comment by evgeth** [comment]
Could you please whitelist zerion.io again? 
Seems that it stopped working for some reason.

**Comment by mqklin** [comment]
We've migrated to Firebase because of this problem

**Comment by sintaxi** [comment]
Hey all, sorry this is a frustrating issue. Just a reminder to get whitelisted you need to DM your email address to the @surge_sh twitter account.

**Comment by eddycaldas** [comment]
hello,

the address is https://eddycaldas.surge.sh/. Allow google doc and pdf please.

Thank you much

Eddy Caldas

________________________________

**Comment by ddiez31** [comment]
Hello @sintaxi Would you mind adding http://david.diez.surge.sh/ to the PDF whitelist as well?
Thank you much

**Comment by rpreilley** [comment]
I just switched to surge and I am in love with the simplicity of the setup. However, I was having this same issue and finally came across this page.

I could really use the ability to have a pdf on my page, as it is for my portfolio and gives easy access to my resume for recruiters without having to request one from me.

If possible, could you please whitelist my site to have this ability. robertreilley.com

I'm sorry you all were targetted by abusers!

Thank you.

**Comment by tavioalves** [comment]
Can you please whitelist my domain?

ezpeed.surge.sh

Thank you!

**Comment by MrXop** [comment]
Happy New Years sintaxi,

Can you please whitelist our domain? www.trulyprotect.com

Thanks!

**Comment by jblacklock** [comment]
Hello @sintaxi!
Can you please whitelist www.jesseblacklock.com?
I would super appreciate it!
Thanks!

**Comment by sintaxi** [comment]
@jblacklock @MrXop @tavioalves done.

**Comment by robhirstio** [comment]
Hi @sintaxi,

Could you please whitelist http://robhirst.io/? I would greatly appreciate it.

Thanks!

**Comment by eric-ls** [comment]
Hello @sintaxi, can you whitelist http://ericls.com? Thanks!

**Comment by konaraddio** [comment]
Hi @sintaxi , can you please whitelist http://omkar.surge.sh? Thanks in advance!

**Comment by kunall17** [comment]
Hey @sintaxi I have to upload my resume pdf on my site so please add http://kunall17.com to the list! :)

**Comment by sintaxi** [comment]
@robhirstio, @eric-ls, @konaraddio, @kunall17 Thanks for waiting. yall should be good now.

**Comment by kunall17** [comment]
Thanks for adding :)

**Comment by zimbeta** [comment]
@sintaxi Another resume site here. Can you please whitelist [tinyvibrations.com](http://tinyvibrations.com/) and [zimbeta.com](http://zimbeta.com/)? Many thanks!

**Comment by TrevBo25** [comment]
Hey @sintaxi I'm just following trend here. Can you whitelist my portfolio site http://trevthedev.surge.sh/ I would like to have my resume view-able.

**Comment by marktheis** [comment]
@sintaxi Could you whitelist my portfolio as well? markthe.is

**Comment by ryanmjacobs** [comment]
@sintaxi Hi can I get my domain whitelisted? I really would like to continue hosting my resume.

CNAME is rmj.us

**Comment by sintaxi** [comment]
@zimbeta @TrevBo25 @marktheis @ryanmjacobs all set!

**Comment by jadiego** [comment]
@sintaxi Can i also get my domain whitelisted? [jadiego.me](http://jadiego.me/) It's also a portfolio site. Thanks!

**Comment by denaillc** [comment]
Hi can you whitelist my site too ? cldn.surge.sh . Thanks 👍

**Comment by brayhoward** [comment]
Sorry to hear about all the abuse. Can I get [http://eastnashvillerestaurantweek.com](http://eastnashvillerestaurantweek.com) added to the whitelist please? 

Thanks in Advance! 🙏

**Comment by callumprentice** [comment]
May I please have my own, personal site whitelisted - callum.surge.sh - thank you!

**Comment by panashemahachi** [comment]
Can .I get l4.ventures added to the whitelist? Thanks!

**Comment by vernilli** [comment]
@sintaxi Could you whitelist my portfolio? http://vernilli.com/

Thanks

**Comment by Haskiez** [comment]
@sintaxi Hey sorry about all the abuse that's been happening. I have a few pdf to upload for my schools development club. Could you whitelist our domain? http://uvudevclub.org/
Thanks in Advance

**Comment by madhavrathi** [comment]
@sintaxi Could you please whitelist my portfolio : http://madhavrathi.surge.sh/
Thanks in advance.

**Comment by Lisamarie73187** [comment]
@sintaxi can you please whitelist my portfolio as well. http://lisamarieherzberg.surge.sh/!
Thank you!

**Comment by bomatson** [comment]
would you mind whitelisting http://fewd.club/? Thanks!

**Comment by kearnie** [comment]
hello, may you please whitelist [kearnie.com](url) please? the pdf is my resume-- thank you!

**Comment by mickr** [comment]
Guess I'll add on, can you please whitelist evilbits.io. Thank you!

**Comment by christopher-wong** [comment]
@sintaxi could you whitelist https://christopherwong.co? I want to link my PDF resume.

**Comment by darron** [comment]
@sintaxi Can you please whitelist these domains please:

www.divescapes.ca
divescapes.ca

Thanks!

**Comment by er3n** [comment]
Can you please whitelist these domains please:
www.bagimsizarabuluculardernegi.org

**Comment by kajoban** [comment]
can you please whitelist kajoban.surge.sh ? Thank you, love your service!

**Comment by hkedia321** [comment]
@sintaxi Please whitelist my domains: harshitkedia.tech and marimuthuk.com

**Comment by bsradcliffe** [comment]
@sintaxi Can you whitelist benradcliffe.com? Hosting resume and portfolio works. Thanks!

**Comment by jakebian** [comment]
Hi, can you whitelist jake.run?

**Comment by dan2600** [comment]
love surge, only have one, so just moved my pdf to another cdn. However, could you all include a warning somewhere about PDFs? There are people like me who do **way** to much work before finally googling "surge.sh pdf not working" and find this thread.  :-p

**Comment by sebbean** [comment]
can you whitelist: http://bean-listen-unmoored.surge.sh ?

**Comment by franky47** [comment]
@sintaxi could you please whitelist my wife's home page (her CV is in PDF) at https://penelopebuckley.com and my own (same reason but not yet deployed) at https://francoisbest.com ?

Thanks a lot !

**Comment by matyasfodor** [comment]
It's very easy to bypass this filter, by simply using a different extension. If someone wants to do something malicious, they'll do this extra mile. (changing the extension on the frontend is very easy) I'm not quite sure if this ban on pdf files makes sense since this is a bunch of extra work for you seeing the number of requests. I also lost 20 precious minutes at least trying to figure this out.

**Comment by silentrob** [comment]
Why not just make supporting PDF's a paid feature?

**Comment by MohammedAijaaz** [comment]
Please white list https://aijaaz-expo.surge.sh, I jushave 2 pdfs. Thanks

**Comment by MohammedAijaaz** [comment]
@sintaxi it would be awesome if there was a certain limit on the number or size of the PDFs that way there would be no hassle with this.

**Comment by ashri** [comment]
@sintaxi could you please whitelist our community kindergarten web site?:

[https://www.seaviewkindy.com.au](https://www.seaviewkindy.com.au)

Our application form is a PDF and so are our information on the intake boundaries.

Thanks for the excellent service.

**Comment by rechutox** [comment]
Please could you whitelist tribality.surge.sh? My CV is a PDF. Thanks!

**Comment by aprct** [comment]
Can you please whitelist https://holycrosssacramento.org ? We're serving our newsletter as a PDF. Thanks!

**Comment by lucaskuzma** [comment]
@sintaxi can you please whitelist my personal site http://lucaskuzma.com

**Comment by girishramnani** [comment]
please whitelist https://clan5.org

**Comment by billfienberg** [comment]
please whitelist https://lindseypayton.com/

**Comment by tolicodes** [comment]
Hello, can you please whitelist my domain (tolicodes.com) or account (adz@nycitt.com) so that I can publish a pdf (my resume) to /resume.pdf? Thanks!

Also a few more domains I eventually plan on publishing some documents to:
- oselot.com
- nycitt.com

**Comment by Roselou** [comment]
Mine too, please! http://roselou.surge.sh/static/media/webdev_resume.5ec3cd54.pdf

**Comment by pixeltopic** [comment]
Can you please whitelist http://kennyjue.com/ ? Needed to upload my resume. Thanks!

**Comment by cravindra** [comment]
Hello @sintaxi . I love surge and the work that you do. I'm really sorry about the abuse. Please whitelist my personal portfolio website chiragravindra.info

**Comment by sintaxi** [comment]
Hey folks, the PDF whitelist requests have piled up so we have implemented a way you can whitelist yourself by running `surge card` and adding a valid payment method to your surge account. This will not charge your account but will give us appropriate protection against abuse. All paying customers now automatically are whitelisted.

We regret we have had to add this friction to our system but unfortunately it has been necessary for keeping our platform stable and keeping our resources on tasks that help all our users.

Thanks for your understanding. Again, add a payment method by running `surge card` to have your account whitelisted for PDFs.

**Comment by callumprentice** [comment]
Worked like a charm for me - thank you.

Can you outline under what circumstances our card will be charged though?
There isn't a scenario where we push one too many projects and get a huge
bill is there?

**Comment by pixeltopic** [comment]
Doesn't work for me - after typing in my cvc and submitting, I get this error:
`undefined:1
<html><body><h1>502 Bad Gateway</h1>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\zzzz\AppData\Roaming\npm\node_modules\surge\lib\middleware\setcard.js:40:24)
    at Request.self.callback (C:\Users\zzzz\AppData\Roaming\npm\node_modules\surge\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\zzzz\AppData\Roaming\npm\node_modules\surge\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\zzzz\AppData\Roaming\npm\node_modules\surge\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)`

**Comment by PetraArkian** [comment]
@sintaxi could you please whitelist my domain? sammylincroft.surge.sh it is for my personal site and contains my resume as well as 4 pieces of writing I've done. I tried to run surge card and it did not work. "Aborted. No such file or directory card"

**Comment by aliogaili** [comment]
@sintaxi  I'm running into similar issue ("Aborted. No such file or directory card").

My domain is resume http://resume.aogaili.com/ if you can still whitelist domain.

**Comment by hkedia321** [comment]
Please whitelist my domain: `http://status-check.surge.sh`. Its urgent. Thanks!

**Comment by zequnyu** [comment]
Please whitelist `zequnyu.com` Thank you!

**Comment by sintaxi** [comment]
Hey folks, I', locking this conversation because you can now self whitelist by running `surge card` and adding a payment method to your account. Just make sure you're on the latest version of surge via `npm install -g surge`.

No charges apply and you wont get unexpected charges based on usage or anything like that. You will only ever get charged if you upgrade to a plan.
