### ISSUE TITLE
SOCKS Proxy support

### ISSUE THREAD

**Issue by ghost** [sintaxi/surge#262]
I need to use SOCKS proxy. Would you include this feature?

surge --proxy="socks5://1.2.3.4:56"

> --proxy="protocol://IP:Port"
> http
> socks5

**Comment by yoursoftwarebug** [comment]
My acquaintance already emailed about this to Surge.sh, but they ignored one's message completely.

Also, please include a guide for proxy users for installation step.
npm --use-proxy --install surge --- something like this

**Comment by yoursoftwarebug** [comment]
or HTTP proxy support, npm already supported it.

**Comment by proxyusertryingsurge** [comment]
Surge didn't read npmjs proxy settings. WTF

**Comment by sintaxi** [comment]
The surge CLI ensures you have an encrypted connection to our publishing interface to help prevent MITMA. This is a feature for the vast majority of people using surge.

The best solution I can suggest at this time is to whitelist `surge.surge.sh` on your proxy. Or to deploy from the proxy itself. It should get you around the issue.
