### ISSUE TITLE
HTTP Proxy Support

### ISSUE THREAD

**Issue by proxyusertryingsurge** [sintaxi/surge#270]
Related to https://github.com/sintaxi/surge/issues/262 , but I really think Surge should have HTTP proxy support.

It is already possible to install Surge on [pcorporate network via HTTP proxy](http://wil.boayue.com/blog/2013/06/14/using-npm-behind-a-proxy/). After the user install Surge, one can't simply use it because it doesn't read npm proxy settings.

If you don't want to read npm settings, why not allow user to specify proxy server, like this:

> surge --project /path/ --domain my.surge.sh --httpproxy=10.0.0.0:1234
> --httpproxy={IP}:{PORT} if set, Surge will use this proxy

> https://stackoverflow.com/questions/3862813/how-can-i-use-an-http-proxy-with-node-js-http-client
> request({proxy: 'http://10.0.0.0:1234',...}...
> (I've tried modified surge code but failed)

**Comment by sintaxi** [comment]
Surge is designed to have a secure connection to surge.surge.sh to prevent MITMA.

I suggest whitelisting `surge.surge.sh` in your proxy.
