### ISSUE TITLE
Unable to enter input for some fields when using Node 8

### ISSUE THREAD

**Issue by xuey90** [sintaxi/surge#272]
Using Node 8 (8.1.0), I tried to perform a `surge login`

I was able to input my email.
I was unable to enter any password. `ctrl + c` did not work either

When I switched back to Node 6 (6.9.1)
I was able to enter both email and password

**Comment by sintaxi** [comment]
A few people have reported this issue but I haven't been able to recreate the problem. What OS are you running?

**Comment by jiverson** [comment]
Same here and to note I am using nvm as well.

**Comment by jesseminn** [comment]
Same here, unable to change the domain name, also unable to enter password when I was trying to login.

**Comment by sintaxi** [comment]
What OS are you all running?

**Comment by xuey90** [comment]
I'm on Mac OS. Happens on both iterm2 and terminal. Also using nvm

**Comment by jesseminn** [comment]
I'm using OSX, I could use it yesterday until I upgraded to 10.12.6 beta last night.

**Comment by xuey90** [comment]
This might be a Node.js issue as my friend had trouble publishing to npm registry on password input. (on Node 8.1.0, Mac OS)

**Comment by xuey90** [comment]
Fixed by upgrading to Node 8.1.2

**Comment by sintaxi** [comment]
@xuey90 thanks for testing and reporting.
