### ISSUE TITLE
Filling the password field doesn't work in Node 8 (macOS)

### ISSUE THREAD

**Issue by K0ff33** [sintaxi/surge#274]
I couldn't fill in the password field when using `surge` for the first time, as the input basically froze.

It's definitely a Node 8 thing, as everything works perfectly fine in Node 6.

`$ surge --version`
`0.19.0`
`$ node --version`
`v8.1.0`
`$ npm --version`
`5.0.4`

macOS running zsh

**Comment by overint** [comment]
Exact same problem here running windows.

surge --version
0.19.0
node --version
v8.1.0
npm --version
5.0.3

**Comment by overint** [comment]
@sintaxi 
Any updates on this?

**Comment by brandonb927** [comment]
@K0ff33 @overint is this still an issue using node v8.9 and latest surge version?

**Comment by K0ff33** [comment]
@brandonb927 nope, all works perfectly fine.

**Comment by sintaxi** [comment]
Sorry, should have closed this ticket. Thanks @K0ff33
