### ISSUE TITLE
Images missing on site.

### ISSUE THREAD

**Issue by organnoise** [sintaxi/surge#279]
I don't see a pattern in this problem:

I have pushed my site. It works locally exactly as I expect.

For some reason when I push to surge <b>certain images are missing</b>. If you run the console you will see which ones are missing. The missing pictures are no bigger than any other file, so I don't know what differentiates them from all the other image files.

Here is the site:
```danielmcn.com```

**Comment by organnoise** [comment]
Ok, I see what I did wrong.

I had some uppercase/lowercase differences from my image names to my html. Locally that didn't seem to be problem but uploading it was. Problem solved

**Comment by sintaxi** [comment]
Thanks for reporting the fix. Closing.

**Comment by InnaMeleshko** [comment]
i still have the same problem )i have 8 images in catalog "images'" in src , but when I push to surge 5 images are missing. checked everyrhing^ still can't find out what he problem is

**Comment by sintaxi** [comment]
@InnaMeleshko We can look into this for you but I need more information. Can you please email support@surgre.sh with more details such as your domain name.

**Comment by sintaxi** [comment]
@InnaMeleshko that email is support@surge.sh rather. Sorry for the typo.
