### ISSUE TITLE
Not ignoring folders that begin with a dot

### ISSUE THREAD

**Issue by edadams** [sintaxi/surge#281]
Hey!

I'm trying to use Let's Encrypt on my Surge.sh site [with the help of this wonderful resource I found.](https://gethttpsforfree.com/)

One of the last steps is to upload files into a folder on my site, `/.well-known/<long string of characters>/`. I'm not able to upload the folder because according to #61 Surge ignores files and folders that begin with a dot.

Is it possible for me to make Surge upload the files in my `.well-known` folder?

If I could also ask, please consider updating Surge so that it makes an exception for the `.well-known` folder. I am doing this for the same reason everyone else is: Google have said HTTPS will be a ranking signal, and soon Chrome may display warnings on non-HTTPS sites. At the same time I know Surge has a Plus package that includes SSL so I see how you're in a tight spot, but I think this would be a cool thing to do so that users like me who have time but not money can get HTTPS.

**Comment by edadams** [comment]
I was misinformed about how HTTPS works on Surge for custom domain names. This is a dead end. I couldn't get my `/.well-known` directory uploaded, nor could I use the `surge ssl` command. The command prompted me for a `pem` file, but when I used my self-signed certificate, it started trying to sign me up for their paid service. Free HTTPS via Let's Encrypt on Surge does not seem to be possible.

To anyone who find thiss on Google: I've now discovered [Surge tweeted saying they will only support Let's Encrypt on their paid plan.](https://twitter.com/surge_sh/status/681928202881642496) 
 
To the developers: Please reconsider this and let us use Let's Encrypt for free. I know it's part of your business model right now but it feels more and more like websites that don't have HTTPS are being treated as "second-class citizens", so even though my personal and side projects don't actually need HTTPS it'd be really nice to have the option of supporting it through Surge. 
 
Closing.

**Comment by franky47** [comment]
Ended up here from a similar issue: I can't upload either `/.well-known/security.txt` (from https://securitytxt.org/) or my Keybase proof (`/.well-known/keybase.txt`)
