### ISSUE TITLE
Unable to access routes on my angular2 app

### ISSUE THREAD

**Issue by prakashraman** [sintaxi/surge#283]
Hi

I am able to push my angular application fine. Although, I am unable to access the routes inside of the application. It returns a 404. 

It there any server setting I would need to set for it to deploy angular applications?

**Comment by sintaxi** [comment]
Rename your `index.html` file to `200.html` and you should get what you are looking for.

**Comment by prakashraman** [comment]
Perfect thanks :)

Love the service btw!
