### ISSUE TITLE
gives page not found

### ISSUE THREAD

**Issue by nileshgulia1** [sintaxi/surge#285]
same as #266 
I have deployed my project on  http://dapper-foot.surge.sh/  .when opening it gives page not found.I have also included `index.html` file in root still nothing happens.Please Help me.
![screenshot from 2017-10-02 11-10-43](https://user-images.githubusercontent.com/22280901/31065391-945305ca-a762-11e7-8bdc-a9c8a15bf7e5.png)

**Comment by brandonb927** [comment]
@nileshgulia1 it looks like you deployed the incorrect folder, I can see a `/build/` path appended to every asset in http://dapper-foot.surge.sh/auto.appcache. When you deploy make sure you specify the `build` folder in your project directory to upload!

**Comment by nileshgulia1** [comment]
@brandonb927  looks like i have included homepage in my package.json .after removing it fixes this error. anyways ,thanks for help.
