### ISSUE TITLE
Site is still online after teardown

### ISSUE THREAD

**Issue by kakuevn** [sintaxi/surge#286]
My draft site `http://hirise-draft.surge.sh/` is still online after I `surge teardown` it a couple of days ago.

Let me know if there is something wrong with it.

Thanks!

**Comment by brandonb927** [comment]
@kakuevn if you try tearing your site down again does it work?

**Comment by kakuevn** [comment]
@brandonb927 no, it says "Aborted - unable to remove [site]"

**Comment by brandonb927** [comment]
I'd reach out to @sintaxi on the Slack channel then

**Comment by kakuevn** [comment]
resolved
