### ISSUE TITLE
Index page doesn't show up properly.

### ISSUE THREAD

**Issue by rlam3** [sintaxi/surge#287]
Index page doesn't show up properly.

Unless you tell it to go to /index
tastycuisine.surge.sh
tastycuisine.surge.sh/index

**Comment by sintaxi** [comment]
The md5 matches regardless of which way its downloaded which matches the header. The problem must be in your application code.

- `curl https://tastycuisine.surge.sh/ | md5` returns `313fe56636d8467884d33a2ee50ae9fa`
- `curl https://tastycuisine.surge.sh/index | md5` returns `313fe56636d8467884d33a2ee50ae9fa`

And checking the headers via `curl -I https://tastycuisine.surge.sh`
```
HTTP/1.1 200 OK
Server: SurgeCDN/1.2.0
Date: Tue, 17 Oct 2017 08:37:30 GMT
Cache-Control: public, max-age=31536000, no-cache
ETag: "313fe56636d8467884d33a2ee50ae9fa"
Content-Type: text/html; charset=UTF-8
Accept-Ranges: bytes
Response-Time: 1ms
Content-Length: 289761
Vary: Accept-Encoding
Connection: close
```

**Comment by rlam3** [comment]
http://tasty-cuisine-nuxt-001.herokuapp.com deployed on heroku with same build and it seems okay...
