### ISSUE TITLE
[Attention! Data tampering] Surge.sh is modifying your "robots.txt" file

### ISSUE THREAD

**Issue by m9491400382** [sintaxi/surge#288]
1. Upload your original project to surge. The project should have "robots.txt", of course.
2. Then, visit your surge.sh website. Add "/robots.txt" to your URL.

Expected result:
Your robots.txt data.

Actual result:
===
User-agent: *
Disallow: /
===

Surge.sh is clearly doing "data tampering".

**Comment by sintaxi** [comment]
For obvious reasons we don't permit search engine indexing on our own domain with other users content. Using a throwaway account to file this issue does not compel me believe the policy is incorrect. A `robots.txt` works as expected with a custom domain.

**Comment by NourddineMaghmouli** [comment]
sorry I am new into this but what you mean by "a robots.txt works as expected with a custom domain", how can I make my website indexed? should I host it as custom domain?

Thanks

Noureddine

**Comment by metasoarous** [comment]
@NourddineMaghmouli Is sounds like this is what he's saying, yes.
