### ISSUE TITLE
Providing an existing domain ends without feedback

### ISSUE THREAD

**Issue by kennethormandy** [sintaxi/surge#29]
If you’re trying to deploy a project to a Surge subdomain that has already been taken, you’ll don’t get any feedback when you’re disallowed. To reproduce, try deploy to this domain I’m already using:

```sh
> surge --domain little-land.surge.sh
```

The flow will end immediately after the domain field is checked:

```bash
> surge --domain little-land.surge.sh
       project path: (/Users/kennethormandy/Desktop/temp12)
               size: 1 files, 34 bytes
             domain: little-land.surge.sh
>
```

**Comment by kennethormandy** [comment]
There’s a nice post-flight in [v0.7.0](https://github.com/sintaxi/surge/releases/tag/v0.7.0) now :cake:

**Comment by kennethormandy** [comment]
Wrong issue, sorry.

**Comment by sintaxi** [comment]
Anyone know if this issue is resolved?

**Comment by kennethormandy** [comment]
Now the flow ends with an error:

```
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

**Comment by sintaxi** [comment]
Thanks. How is it you're testing that? just disconnecting while in a deployment?

**Comment by kennethormandy** [comment]
Oh, this is for trying to deploy to a domain that someone already owns. I don’t think it’s high priority, I am just documenting it (although, this would be the path for the request an invite thing you were proposing. I don’t think we need to do that yet though). You could test it by logging out and trying to deploy to `sintaxi.surge.sh` with a test account.

**Comment by kennethormandy** [comment]
Oh…this seems to be working now. Maybe I was accidentally testing with an old version? Anyway, now I get:

```
Aborted - you must be granted access to publish to cssbrigade.com
```
