### ISSUE TITLE
404 page not found when query params ends with file extension

### ISSUE THREAD

**Issue by adriaanvanrossum** [sintaxi/surge#290]
If I go to my website on surge to this URL: `https://example.com/login?email=test@test.com`, I get this error:

<img src="https://user-images.githubusercontent.com/1079135/31802492-d893dafa-b50b-11e7-9732-43f6510bed85.png" width="450px">

If I go to these URLs it **does** work as expected (no 404):
- `https://example.com/login?email=test@test.com&tralala`
- `https://example.com/?email=test@test.com`
- `https://example.com/login`
- `https://example.com/robots.txt`
- `https://example.com/robots.txt?file=robots.txt`
- `https://example.com/login?email=test@test`

If I go to these URLs it **does not** work as expected (returns 404):
- `https://example.com/login?email=test@test.com`
- `https://example.com/login?file=robots.txt`

It looks like the path of the URL is being checked for a file extension, but also if it is a query parameter. It should only be checked when it is part of the filename.

> I use a [200.html page](https://surge.sh/help/adding-a-200-page-for-client-side-routing) to catch all the 404s which does not work, because I see the surge 404 page.

**Comment by sintaxi** [comment]
Thanks for the detailed report. Taking a look.

**Comment by sintaxi** [comment]
Just released a fix for this issue. Please let me know if you find any other problems.

**Comment by adriaanvanrossum** [comment]
Works for me now, thanks!
