### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MaxShalom** [sintaxi/surge#294]
Followed tutorial, added very simple Index.html file and ran surge in the command line to get the confirmation: Success!

However, as you can see in the picture below, i get a 404 and the website is not found.

![image](https://user-images.githubusercontent.com/23295246/32642072-dd35e3f6-c59f-11e7-8a2a-1b1605031e06.png)

What can I do to fix my problem?

Thanks

**Comment by RMCoder198** [comment]
Its working .
http://wide-pets.surge.sh/

**Comment by MaxShalom** [comment]
It has been fixed.
