### ISSUE TITLE
Deployment always gets stuck

### ISSUE THREAD

**Issue by codejet** [sintaxi/surge#295]
I just started using surge earlier. Verified my email and wanted to deploy a small Gatsby project (I'm running macOS sierra and using iTerm). I ran the surge command, giving it the public directory.  But the deployment always gets stuck at the point where it shows the domain. 

```
Surge - surge.sh

email: [my verified email]
token: *****************
project path: public
size: 130 files, 10.7 MB
domain: something.surge.sh
```

When I abort it says "Please try again with a valid domain name."

I already went through the issues here but found nothing which helped with my issue unfortunately...

**Comment by jklegseth** [comment]
@codejet would have been great to add what you did to solve this before closing.

**Comment by danielmahon** [comment]
To anyone who got here... the `domain: something.surge.sh` line is interactive (the terminal cursor is at the end of .sh), you can either modify the domain (backspace and type) or just hit enter to stick with the default.

**Comment by matthodgson** [comment]
@danielmahon Thanks for posting this. I feel pretty dumb for not noticing that.

**Comment by chrisbradshaw** [comment]
I made the same mistake.. maybe there should be a prompt like:

project: public/
domain ("enter" for default):
