### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by silentrob** [sintaxi/surge#30]
I always seem to forget the bloody thing, it would be nice to have a reset flow.

**Comment by cfjedimaster** [comment]
+1 on this (I tested surge a while ago and apparently used a password I don't remember ;)

**Comment by monfresh** [comment]
+1. I used 1Password to generate my password but didn't save it. Also, I would recommend defaulting to sending the password reset email, without checking if the email already exists. For security and privacy reasons, you don't want to reveal whether or not an email exists in your system.

**Comment by bmds** [comment]
We've already hit this issue. I gave a junior dev a small bug fix then deploy task on a site. He created an account then immediately forgot the password. I ended up pushing it up.

**Comment by kennethormandy** [comment]
As an update to this issue, you can now [reset your password via the CLI](https://surge.sh/help/resetting-your-password). Thanks for your patience!

First, upgrade to the latest version of Surge:

```
npm install -g surge
```

Then, you can reset your password:

[![](https://surge.sh/images/help/resetting-your-password.gif)](https://surge.sh/help/resetting-your-password)

If you have any questions, feel free to ask in [our chat room](https://surge.sh/help/chat).

**Comment by Vishala09** [comment]
I am getting this error!
Please some one help 

```
surge

   Welcome to surge! (surge.sh)
   Login (or create surge account) by entering email & password.

          email: vishala.ramasamy@gmail.com
       password:
       password:
       password:
         forgot? (yes) yes

   Oops - something went wrong trying to reset your password.
```
