### ISSUE TITLE
Failed to load resource: the server responded with a status of 404

### ISSUE THREAD

**Issue by namminammi** [sintaxi/surge#300]
I've deployed my [React app](http://qq4.surge.sh) and it's getting "Failed to load resource: the server responded with a status of 404" error, and none of css or js is loading. I'm using the [create-react-app boilerplate ](https://github.com/facebookincubator/create-react-app) and deploying from my-app/build. It works properly in my localhost:3000. What could be the issue?
<img width="1167" alt="screen shot 2018-01-02 at 1 11 53 pm" src="https://user-images.githubusercontent.com/8492625/34494459-9be6fdd8-efbe-11e7-8dd4-df784af974e8.png">
<img width="1153" alt="screen shot 2018-01-02 at 1 12 15 pm" src="https://user-images.githubusercontent.com/8492625/34494460-9bf2a390-efbe-11e7-9b69-1e5a5b218f0f.png">

**Comment by namminammi** [comment]
It happened that the build command didn't remove the root folder from the path and once it was removed index.html could locate all resources again.

**Comment by AnaitBI** [comment]
@namminammi 
How to do that?

**Comment by Sean-93** [comment]
yeah, how do you do that

**Comment by UmairHussain123** [comment]
but how to do that
