### ISSUE TITLE
Deployment always hangs.

### ISSUE THREAD

**Issue by FullstackJack** [sintaxi/surge#305]
The `surge public/` command recommended in the Gatsby documentation hangs. I signed up using the `surge` command and verified my email address.  

```
Surge - surge.sh

              email: [verified email]
              token: *****************
       project path: public/
               size: 68 files, 7.2 MB
             domain: clammy-club.surge.sh
```

The process never finishes so I am forced to CTRL + C. When I do, the following message shows up:
`Aborted - Please try again with a valid domain name.`

No word on if it is caused by my corporate firewall but it might be.

MacOS 10.12.6

**Comment by FullstackJack** [comment]
Alright, I can publish from the app root, but that takes the src and everything else to the server. Public will not copy on it's own.

**Comment by sintaxi** [comment]
pretty sure you just need to hit `enter`. because you did not pass in a domain you are being prompted with `clammy-club.surge.sh` as a suggestion.

**Comment by irtaza909** [comment]
> pretty sure you just need to hit `enter`. because you did not pass in a domain you are being prompted with `clammy-club.surge.sh` as a suggestion.

hahahahah i spent whole day why is it not working :)

**Comment by sintaxi** [comment]
@irtaza909 sorry to hear that. In the future we will be encouraging people to use the shorthand `surge path/to/www example.com`. OR `surge path/to/www _` if they need a subdomain selected for them.
