### ISSUE TITLE
Surge List not working

### ISSUE THREAD

**Issue by MightyRevenge** [sintaxi/surge#307]
![1 bash 2018-03-03 12-17-32](https://user-images.githubusercontent.com/5233993/36937144-e9989954-1edc-11e8-92a3-d019717913f1.png)

Surge list just shows [object Object], the data hasn't been converted properly for viewing? I can PR.

**Comment by TmszLBmrv** [comment]
It's been fixed. Update surge to newest version.

**Comment by plumpNation** [comment]
I had the same issue.

I did a npm uninstall and reinstall to upgrade. Ran `surge list`.

```
... .nvm/versions/node/v9.3.0/lib/node_modules/surge/lib/middleware/list.js:45
project.timeAgoInWords.grey

TypeError: Cannot read property 'grey' of undefined
```

nodejs 9.3.0
npm 5.6.0

Thanks for the tool, I've not had any issues before.

**Comment by skoldborg** [comment]
I'm having the same issue and I'm on the latest version (0.20.1).

**Comment by jonnyburch** [comment]
Still getting this issue. How do I fix?

**Comment by albertkim** [comment]
This is definitely still an issue - is Surge still active and maintaining their product? I installed the latest using `npm install -g surge`

**Comment by kaicianflone** [comment]
@albertkim You might have a messed up global ENV if you've used Yarn and NPM. Running `npm install -g surge` fixed the issue for me :)

Try deleting yarn.lock / package.json.lock and rerunning the npm command

**Comment by jezen** [comment]
This is _not_ still an issue. Check your surge version in your package.json or similar.

**Comment by MightyRevenge** [comment]
Updated version fixes issue.

**Comment by rtablada** [comment]
I have completely uninstalled and reinstalled on two machines and still get the error property grey of undefined.

Version info:
`surge – single command web publishing. (v0.21.3)`

**Comment by rtablada** [comment]
I was able to test and figured out that some projects come back from the api with no value for `timeAgoInWords`, `platform`, or `cmd`.

Either this is a regression in the API or the CLI should be able to gracefully handle projects that don't have those values.

**Comment by sintaxi** [comment]
@rtablada Interesting. can you email support@surge.sh with some more details so we can dig into this issue?

**Comment by nathanaelphilip** [comment]
having this issue as well – 10.14.6 – let me know what you need
surge version `v0.21.3`

**Comment by AlexM566** [comment]
Hello


```
C:\Users\\AppData\Roaming\npm\node_modules\surge\lib\middleware\util\helpers.js:145
      if (e) throw e
             ^

I have the following error trying to login in surge:
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}

Node.js v17.3.0
```
I tried everything I found here but is not working...
Is there any fix?
