### ISSUE TITLE
Certficate expired error

### ISSUE THREAD

**Issue by jineshshah36** [sintaxi/surge#313]
No matter what I try to do from the cli, I get this:

<img width="737" alt="screenshot 2018-03-08 19 19 12" src="https://user-images.githubusercontent.com/6501089/37184229-3a8155a2-2308-11e8-8df3-0de060da3cdf.png">

**Comment by nk1tz** [comment]
Having the same problem.

**Comment by fbonetti** [comment]
Same problem. I can't deploy.

**Comment by sintaxi** [comment]
Resolved. FWIW - This only affected the deployment server.
