### ISSUE TITLE
Cache problem while updating a current project

### ISSUE THREAD

**Issue by sbstnplcn** [sintaxi/surge#318]
Hello,

I have a cache problem while updating a current project.
I need to teardown the project, then recreate it to have the last version of my code available online.

Any idea ? 
Thanks

Working on Vue.js and Quasar PWA framework.
Node v9.8.0

**Comment by sintaxi** [comment]
That's strange. Can you show me steps to reproduce the problem?

**Comment by Lupshenko** [comment]
I have exactly the same problem

How to reproduce:
1. Deploy an example site (I deployed it with one empty text file "a.txt")
2. Delete one random file from the project (in my case "a.txt")
3. It will be still there

How to fix it temporarily:
1. Try redeploying the site again (1-3 times in my case)

**Comment by sintaxi** [comment]
@Lupshenko thanks. Can you let me know what version of surge you are on? and what OS you are using? Cheers.

**Comment by sintaxi** [comment]
Thanks for your help. I've been able to implement a fix. Please reopen if you still have issues.

**Comment by Lupshenko** [comment]
Still occurs for big files. I used a 7mb tarball and an urandom filled 30mb raw file. Everything was tested on a RAM disk under Arch based GNU/Linux distro with curl and Surge 0.21.0
