### ISSUE TITLE
Big files caching problem

### ISSUE THREAD

**Issue by Lupshenko** [sintaxi/surge#321]
Surge still have a problem with file caching (after uploading, deleting or updating) but now it occurs only on big files and gets worse as the file size increases

The files I used to test this are attached. To upload the first, I have to deploy the site, wait about a minute and redeploy it again. For the second, I have to do the same but wait much longer

Some data, maybe it'll help:
OS: Arch based GNU/Linux distro
Surge: 0.21.0 (latest from npm)
Browser: curl

[a.tar.gz](https://github.com/sintaxi/surge/files/1907577/a.tar.gz)
[b.txt](https://github.com/sintaxi/surge/files/1907580/b.txt)

**Comment by sintaxi** [comment]
Thanks for reporting. We have been in contact with Digital Ocean provider and they saw issues with the CPU load of on one of our machines so the have migrated it to a better location. That should take care of this problem. Please let us know if you still see the problem.
