### ISSUE TITLE
Problem deploying to a specific URL

### ISSUE THREAD

**Issue by baristaGeek** [sintaxi/surge#322]
I've been using surge for the past 2 months and during this time it hasn't presented any issues when deploying to certain URL. However, I recently deployed some code to such URL and to my surprise the deployed version of the code was the previous one (despite surge notifying a successful deploy). I thought that it might have been a problem with the browser's cache, so I decided to clean it and the problem persists. I also experimented deploying to some other random URL, and the deployed version is the new code.

What might be wrong?

**Comment by sintaxi** [comment]
A lot has happened on our backend this week. I see you closed the ticket but if your still looking for an explanation I'll review and get back to you on this.

**Comment by baristaGeek** [comment]
@sintaxi thank you so much for your response! I did see your Twitter and saw on StackOverflow people with similar issues. I just re-deployed a few hours later and that was it.
