### ISSUE TITLE
Surge list not working

### ISSUE THREAD

**Issue by izanf** [sintaxi/surge#324]
The command `surge list` is not working, the return of the command is `
      [object Object]
      [object Object]
      [object Object]
      [object Object]
      [object Object]
`

**Comment by sintaxi** [comment]
@matteodem upgrade to latest version of surge. let me know if its still an issue.

**Comment by matteodem** [comment]
Oh okay that helped. Thanks!

**Comment by sintaxi** [comment]
hmmm, I wonder why `npm update` didn't work. /shrug
