### ISSUE TITLE
How to update? Running `surge public/` multiple times creates new domains. 

### ISSUE THREAD

**Issue by skube** [sintaxi/surge#327]
I can publish to a surge domain by running `surge public/`.

I make changes in `public/` 

How do I now update the surge domain? 

Running `surge public/` simply creates a new, random surge domain.

What am I not understanding?

**Comment by sintaxi** [comment]
pass in a second argument eg. `surge public mydomain.surge.sh`

**Comment by skube** [comment]
Thanks. 😄 

Seems to me this could be a slightly better and more intuitive experience. 

Something like `surge public update` would 1) save having to remember the domain used and 2) prevent having to type in the long domain.

**Comment by sintaxi** [comment]
Your can add your domain to a `CNAME` file in the root of your public folder and it will get picked up giving your the experience you want.

Also the following accomplishes the same thing...

- `surge --project public --doamin example.com`
- `surge -p public -d example.com`
- `surge public example.com`

The CLI design is intended to mimic the `mv` command in unix https://www.computerhope.com/unix/umv.htm
