### ISSUE TITLE
wat

### ISSUE THREAD

**Issue by k1r0s** [sintaxi/surge#332]
> I have the latest version installed

$ surge list 

```
    Surge - surge.sh

              email: ciro@mint-labs.com
              token: *****************

      [object Object]
      [object Object]
      [object Object]
      [object Object]
      [object Object]
      [object Object]
      [object Object]
      [object Object]
      [object Object]

```

**Comment by sintaxi** [comment]
are you on the latest version of surge? `npm install -g surge`.

**Comment by k1r0s** [comment]
I just said, yes

**Comment by k1r0s** [comment]
however this issue is solved. I tried many times till it was success :\

**Comment by k1r0s** [comment]
Aborted - Unable to remove qmenta-preview.surge.sh.

But qmenta-preview.surge.sh is still online 

What I can do to solve this?
