### ISSUE TITLE
Still waits to propagate removed files

### ISSUE THREAD

**Issue by kennethormandy** [sintaxi/surge#34]
What I did:

1. Accidentally started deploying my source directory
2. Bailed with `CRTL+C` at around 20%
3. Redeployed the correct directory

Expected:

This only uploaded 1 file, only 1 file is propigated.

Actual:

Only 1 file is uploaded, but still waited to do the “Propigate on CDN” thing for all the accidentally uploaded files. I believe this caused a restart, we got a Papertrail notification. Also it’s still only at 6% after about a minute.

**Comment by silentrob** [comment]
I just pushed code in slushi to address this. 
Please re-test.

If you ctrl+c in the first step, we abort, if you cancel in propagate stage, it will continue.

**Comment by kennethormandy** [comment]
:ok_hand: Nice work @silentrob
