### ISSUE TITLE
Getting "Aborted - Unable to publish. Application too large"

### ISSUE THREAD

**Issue by rabimba** [sintaxi/surge#341]
So I am trying to publish a stalk slide (and frankly it has a few very big images in it). Was wondering what is the file size limit for any surge project?

**Comment by alisonjoseph** [comment]
I'm also running into this issue. What is the max size?

**Comment by PolGuixe** [comment]
Also running into this issue. Not from local but from Gitlab pipelines.

**Comment by DanySK** [comment]
I hit it once when generating Kotlin/Dokka for a big project (no images, the website was above 50MB though).
It was some time ago, I don't know if the limit is higher now.

**Comment by bdrtsky** [comment]
Any chance to answer that, hello?

**Comment by sintaxi** [comment]
The limit is set to 4500 files and about 450MB. You may want to look into using `.surgeignore` file to omit deploying certain files. https://surge.sh/help/ignoring-files-and-directories

**Comment by xrkffgg** [comment]
@sintaxi HI, I have a project with 600MB after build, is there any way to publish it? Thank you!!!

**Comment by Sina-Hosseini-GST** [comment]
> @sintaxi HI, I have a project with 600MB after build, is there any way to publish it? Thank you!!!

Hi there
Could you publish it?

**Comment by sojs-coder** [comment]
Mine is running 12098 and 1.5GB..... kept getting error  `Aborted - you do not have permission to publish to <some_name>`. Read #179  but it did not fix anything (started adding completely random characters to the domain, nothing worked, even though when I checked no site was hosted there). Not getting "Application too large" though so not quite sure what to do... It would seem logical this is my error though.
