### ISSUE TITLE
Error - Deployment did not succeed.

### ISSUE THREAD

**Issue by aashutoshrathi** [sintaxi/surge#348]
After upload and CDN are 100% completed it throws an error.

`Error - Deployment did not succeed.`

**Comment by sintaxi** [comment]
Pretty sure this was resolved a few hours ago. When is the last time you tested?

**Comment by aashutoshrathi** [comment]
Yes, this is fixed now.
Thanks ❤️

**Comment by keligijus** [comment]
hey, anyone facing this again?

I get both upload and CDN to 100% just to be followed by `Error - Deployment did not succeed.`
