### ISSUE TITLE
--token not working

### ISSUE THREAD

**Issue by YashKumarVerma** [sintaxi/surge#355]
i've added the SURGE_TOKEN and SURGE_LOGIN env variables in travis
but this command

surge --project ./ -d https://***.surge.sh --token $SURGE_TOKEN

asks to enter credentials
![image](https://user-images.githubusercontent.com/14032427/47767554-2c6bd800-dcfa-11e8-9622-1638b1993183.png)

**Comment by Platane** [comment]
One workaround is to have `SURGE_LOGIN` and `SURGE_TOKEN` exposed as env var

As defined in this file : https://github.com/sintaxi/surge/blob/1b947a522c9403166a9c2c28120514a57b4ffcc1/lib/middleware/util/creds.js#L23

**Comment by sintaxi** [comment]
This should now be resolved. Setting `SURGE_TOKEN` as en environment variable or passing in a literal token in the `--token` works on the latest version of surge.

**Comment by tpluscode** [comment]
Hm, I just tried the env variable and it did not work. The `--token` param works though
