### ISSUE TITLE
GIFs are no longer being served?

### ISSUE THREAD

**Issue by dan2600** [sintaxi/surge#358]
Hi, I'm not sure when this happened, but when i went on to my surge hosted site today, none of the gif images I have uploaded are working anymore. They are returning a valid response, but 0 bytes.

example 

http://dan2600.com/images/p5000/hero.gif

Accept-Ranges: bytes
Cache-Control: public, max-age=31536000, no-cache
Connection: close
Content-Length: 0
Content-Type: image/gif
Date: Wed, 19 Dec 2018 22:31:59 GMT
ETag: "01887284048c49864cb8a9867e7b4ab3"
Response-Time: 1ms
Server: SurgeCDN/1.2.0

**Comment by sintaxi** [comment]
Hmm. I'll look into this.

**Comment by dan2600** [comment]
Thanks! To give you some more context, I know it was working last week, and pretty sure as recent as this weekend. I haven't looked at the site in a day or two.  I also tried re-uploading the site just to make sure, but the result is the same. Thank you so much for checking!

**Comment by sintaxi** [comment]
We appear to have a saturated disk which left some files corrupted. Well be clearing the caches but there could be some invalid browser side caches. We'll find a way to bust those caches on our end but it could take us a bit of time. 

Do you have any other examples you can send to us?

**Comment by sintaxi** [comment]
I think all assets should be loading correctly now. Let me know if you still see any errors. We will have to do more tweaking with the caches but we are out of the woods from an content delivery error perspective. Thanks for reporting.
