### ISSUE TITLE
Surge not updating

### ISSUE THREAD

**Issue by karsens** [sintaxi/surge#359]
Hi, my project https://communify.cc is not updating when I try to surge. Even teardown has no effect although it says it worked fine. 

Last week I added this to the build to fix some 404 errors that weren't supposed to be there because there actually was a route active on a link but it gave 404.

Don't know if it has anything to do with it but it seemed hacky.

yarn build &&
mv build/index.html build/200.html &&
surge -p build/ -d https://communify.cc

**Comment by fu-sen** [comment]
I have verified WHOIS because you have written the domain concretely:
```
   Domain Name: COMMUNIFY.CC
    :
   Name Server: DANA.NS.CLOUDFLARE.COM
   Name Server: PAUL.NS.CLOUDFLARE.COM
```
This domain uses Cloudflare. Therefore it seems that the cache is working and it is not updated.
First of all, you should log in to Cloudflare and try caching. Perhaps this is not a matter of Surge.

**Comment by karsens** [comment]
@fu-sen Thanks, yes, cloudflare is in between Communify and surge. So
1) disable cache on cloudflare?
2) point my domain directly to surge instead of cloudflare?

**Comment by sintaxi** [comment]
Changed caching headers recently that could be causing the browser too use a cached version. Check to see if a hard refresh `CMD-R` solves the problems.

**Comment by karsens** [comment]
> Changed caching headers recently that could be causing the browser too use a cached version. Check to see if a hard refresh `CMD-R` solves the problems.

No, still the same.

**Comment by fu-sen** [comment]
@karsens  If you are using Surge on Free Plan, you should delete the cache first:
https://support.cloudflare.com/hc/en-us/articles/200169246-How-do-I-purge-my-cache-

Do you remember the chance to introduce Cloudflare?
HTTPS communication? It will be lost when you go directly to Surge!

**Comment by karsens** [comment]
> @fu-sen Thanks, yes, cloudflare is in between Communify and surge. So
> 
> 1. disable cache on cloudflare?
> 2. point my domain directly to surge instead of cloudflare?

I can't do the second because then I loose my protection to my server (which is on a subdomain)..... I can only use one name server...

**Comment by karsens** [comment]
> @karsens If you are using Surge on Free Plan, you should delete the cache first:
> https://support.cloudflare.com/hc/en-us/articles/200169246-How-do-I-purge-my-cache-
> 
> Do you remember the chance to introduce Cloudflare?
> HTTPS communication? It will be lost when you go directly to Surge!

Also true, I need https. I just purged cache :)

**Comment by fu-sen** [comment]
@karsens Have you solved the problem? Please close it when solving.

@sintaxi I feel that several people in #323 have the same problem. I will add comments.

**Comment by karsens** [comment]
> @karsens Have you solved the problem? Please close it when solving.
> 
> @sintaxi I feel that several people in #323 have the same problem. I will add comments.

Yes it worked! The site is new now. So it may have to do with the cloudflare in between. I purged the cache and set it to dev mode. That worked. Or it may have to do with what @sintaxi changed.
