### ISSUE TITLE
Bitbucket pipelines - continuous deployment - prompting issue

### ISSUE THREAD

**Issue by Genenenenaam** [sintaxi/surge#365]
I'm using bitbucket pipelines. But the deployment fails because of surge prompts for email.
I see no flags / options to pass along in the cli.

bitbucket-pipelines.yml
<img width="804" alt="schermafbeelding 2019-02-08 om 14 14 32" src="https://user-images.githubusercontent.com/20650976/52480401-e7cec300-2bab-11e9-94c0-816177626f71.png">

The bitbucket pipeline stops when promted for the email adress (and password next?)
![schermafbeelding 2019-02-08 om 14 16 26](https://user-images.githubusercontent.com/20650976/52480610-7e9b7f80-2bac-11e9-8852-fb7f9bd5c5fe.png)

Is there a way to pass your email (and password) as a flag?

**Comment by fu-sen** [comment]
It is the same problem as this issue. You may be able to use this comment content:
https://github.com/sintaxi/surge/issues/355

**Comment by Genenenenaam** [comment]
$129 a month. No tnx.

**Comment by sintaxi** [comment]
Use `--token` for passing in an access token to any surge command. A token can be generated with the command `surge token`. 

Surge Professional is $30/mo not $129/mo. Not seeing anything here that would require an upgrade to Pro. Looks to me like its just prompting for authentication.

Closing. Please reopen if there is any questions.
