### ISSUE TITLE
[0.21.2] Error: cannot find module "fstream-ignore"

### ISSUE THREAD

**Issue by le0nik** [sintaxi/surge#375]
Size middleware(among others) uses `fstream-ignore`

https://github.com/sintaxi/surge/blob/c61b503a019af9bfe74dc5d54f39dcbeccd2a86a/lib/middleware/size.js#L2

but it's not listed in package.json dependencies. It was changed to `surge-fstream-ignore` in this commit: https://github.com/sintaxi/surge/commit/c2fff29f88728af348142d0a1673a5213f354b59

**Comment by sintaxi** [comment]
Thanks! Just released `v0.21.3` which should resolve the issue.
