### ISSUE TITLE
What data of clients is collected by Surge ?

### ISSUE THREAD

**Issue by YashKumarVerma** [sintaxi/surge#376]
It would be great if we could know what data is collected by surge

**Comment by sintaxi** [comment]
Great question. Surge collects nothing other than the version of the client and the directory/arguments you pass in for your upload. Surge takes your privacy very seriously. Surge does not snoop or sniff around your system like other CLI's do.

The version is only kept for the lifecycle of the request so we can accomodate breaking changes. That is why very old version of surge still work well. The client version not kept on your file.

You can see the code here...

https://github.com/sintaxi/surge/blob/2ed7d79d683e89d0fc6cd5325cdd9f026d6e7f65/lib/middleware/deploy.js#L18-L28

**Comment by YashKumarVerma** [comment]
Thanks for the information. 
I've been in love with Surge for over 2 years now. :heart:
