### ISSUE TITLE
Published to ( Domain.surge.sh ) but actually not deployed or depolyed with big delay

### ISSUE THREAD

**Issue by riiccardo** [sintaxi/surge#377]
I use the surge command to deploy the site

But I'm having a problem with the new version `0.21.3` just error at end of publish 😭 

I'm downgrade to `0.20.5` to solve the error
But after the execution of the command, the site is published in this version, but with a lot of delay the site will be displayed
delay take 5 or 10 min 😢

**Comment by sintaxi** [comment]
I don't think its related to the version of the client you are running. Were seeing a lot of build errors this morning and still trying to get to the bottom of things.

**Comment by patrickmonteiro** [comment]
I still have the same problem. My deploy attempt returns: "Deployment did not succeed."

**Comment by patrickmonteiro** [comment]
I think it can be closed, the problem was solved the same day!
Thanks for the support.

**Comment by sintaxi** [comment]
Thanks Patrick. Closed.
