### ISSUE TITLE
Not available in Russia

### ISSUE THREAD

**Issue by talentlessguy** [sintaxi/surge#378]
I can't use Surge in Russia, it is blocked. Is there any mirror for it?

[Report](https://isitblockedinrussia.com/?host=surge.sh)

![image](https://user-images.githubusercontent.com/35937217/61984807-8e9a0500-b00e-11e9-8f1f-75f43aea0d46.png)

**Comment by jynweythek** [comment]
by Генпрокуратура, заводите ишью на них))))

**Comment by catdrout420** [comment]
talentlessguy im mirroring the surge.sh website for you. it works offline

**Comment by catdrout420** [comment]
Install surge: 
npm install --global surge
# Then in your project folder 
 surge

**Comment by catdrout420** [comment]
> I can't use Surge in Russia, it is blocked. Is there any mirror for it?
> 
> [Report](https://isitblockedinrussia.com/?host=surge.sh)
> 
> ![image](https://user-images.githubusercontent.com/35937217/61984807-8e9a0500-b00e-11e9-8f1f-75f43aea0d46.png)

![Screenshot_20210523_120907](https://user-images.githubusercontent.com/81867095/119259926-006a1800-bbc0-11eb-8d7f-5b3bc6c59834.png)


# Eh no it is not blocked in russia

**Comment by talentlessguy** [comment]
nice it got unblocked

closing then

**Comment by sintaxi** [comment]
Its possible that the IP of our edge node just changed. Anyway, glad to see it unblocked. Thanks for following up!
