### ISSUE TITLE
surge list returns [object Object]

### ISSUE THREAD

**Issue by didaquis** [sintaxi/surge#387]
The command `surge list` returns this:
```

    Surge - surge.sh

              email: example@example.com
              token: **********

      [object Object]
      [object Object]
      [object Object]
      [object Object]

```

**Comment by sintaxi** [comment]
I think you may be on a very old version of surge. Run `surge --version` to check. Run `npm install -g surge` to update.

**Comment by didaquis** [comment]
> I think you may be on a very old version of surge

You are right! Update Surge solve the issue. Thanks
