### ISSUE TITLE
Auth Endpoint Schema is hard coded

### ISSUE THREAD

**Issue by silentrob** [sintaxi/surge#39]
We need to be able to set HTTPS

**Comment by sintaxi** [comment]
hmm, good catch.

**Comment by silentrob** [comment]
I think the right thing and easiest is to assume the endpoint includes the schema 

Here - https://github.com/sintaxi/surge/blob/master/lib/cli.js#L15 
and relax 
https://github.com/sintaxi/surge/blob/master/lib/middleware/auth.js#L10
We could do a check and assume https by default?!?

**Comment by sintaxi** [comment]
makes sense.
