### ISSUE TITLE
Unable to teardown project

### ISSUE THREAD

**Issue by yudhiezk** [sintaxi/surge#393]
I'm unable to teardown project or update the project. I'm using surge version 0.21.3. When I teardown a project, somehow I can still access it. Any idea why?

**Comment by sintaxi** [comment]
Thanks for reporting. If you can come up with a way to duplicate the issue that would be extremely helpful.

**Comment by sintaxi** [comment]
This issue is resolved now. please re-open if you are still having any problems.
