### ISSUE TITLE
routing does not work when several levels of links

### ISSUE THREAD

**Issue by Abdubek** [sintaxi/surge#397]
I added 200.html

http://wtotem.surge.sh/profile - work
http://wtotem.surge.sh/dashboard - work

but if there are several levels, like

http://wtotem.surge.sh/profile/settings - not working

**Comment by sintaxi** [comment]
Are you sure you have a `200.html` file in the root of your project? I'm not seeing one.

**Comment by Abdubek** [comment]
sure.
and if I don’t add a 200.html file, then I can’t directly go to the address http://wtotem.surge.sh/profile

**Comment by Abdubek** [comment]
I understand my problem
Sorry for bothering
