### ISSUE TITLE
Install fails with "'rxjs@^6.4.0' is not in the npm registry"

### ISSUE THREAD

**Issue by StephenCleary** [sintaxi/surge#401]
Just tonight, `npm install -g surge` started failing for me:

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/rxjs/-/rxjs-6.5.5.tgz
npm ERR! 404
npm ERR! 404  'rxjs@^6.4.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'inquirer'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\steph\AppData\Roaming\npm-cache\_logs\2020-04-03T01_39_36_632Z-debug.log
```

Looks like upstream rxjs messed something up and now surge can't install.

[2020-04-03T01_39_36_632Z-debug.log](https://github.com/sintaxi/surge/files/4424609/2020-04-03T01_39_36_632Z-debug.log)

**Comment by StephenCleary** [comment]
And just like that it started working again. Never mind!

**Comment by sintaxi** [comment]
I just tested it myself and it seems to be working. Thanks for following up :)

**Comment by StephenCleary** [comment]
Thanks for a great tool!

If you want to check it out, I threw together a [repo](https://github.com/StephenClearyExamples/PullRequestStaging) to show how GitHub Actions can be used to support slash-commands for pull requests. So I implemented `/deploy` and `/teardown` actions using Surge.sh to give each PR its own staging environment. Started [blogging about it](https://blog.stephencleary.com/2020/04/github-actions-pull-request-staging-environments-part-1.html), too.

**Comment by sintaxi** [comment]
You're welcome! Thanks for sharing your repo and blog. Looks like it could be good reference material.
