### ISSUE TITLE
Surge site availability

### ISSUE THREAD

**Issue by atmollohan** [sintaxi/surge#404]
Are there limitations to the free version of surge. I have a domian: https://weroast.surge.sh/ and when I try to look at the site on my mobils safari I am seeing the surge default 404 page. Is this something that I need to configure in my app?

**Comment by sintaxi** [comment]
It looks to me like you perhaps intended to deploy the `public` directory??

https://weroast.surge.sh/public/

**Comment by atmollohan** [comment]
Oh you're totally right I had updated the domain to default to https and accidentally overwrote the previous domain. I appreciate the help!
