### ISSUE TITLE
Letsencrypt SSL auto-renewal/outtage

### ISSUE THREAD

**Issue by jascodes** [sintaxi/surge#405]
Hey @sintaxi 

Awesome Project..

My domain https://jas.bio is showing expired SSL. Seems like letsencrypt didn't autorenew for some reason. I don't know if its right place to post this. But just wanted to let you know

Jas

**Comment by sintaxi** [comment]
I’ll take a look right away.

**Comment by jascodes** [comment]
Hey @sintaxi 
Did you do something? Because the renewal just happened. Although it expired from yesterday. So there might something going on.

Thx

**Comment by sintaxi** [comment]
Yep, I just provisioned a new cert for you. Not sure why the auto-renew didn't work but we'll look into that. Looks like you're all set.

**Comment by jascodes** [comment]
Hey Thx very much, But can you also for *.jas.bio as well?
That will be really helpful.

Thx

**Comment by jascodes** [comment]
Hey @sintaxi 
I was also curious, do you guys have setup cronjob that tries auto renew for every domain in registry in X days or its more complicated setup?

Jas

**Comment by sintaxi** [comment]
> can you also for *.jas.bio as well?

Unfortunately wildcard certs have to be uploaded with the `surge ssl` command because I don't have those implemented yet on Lets Encrypt. If you have a specific subdomain you want me to provision let me know.

> I was also curious, do you guys have setup cronjob that tries auto renew for every domain in registry in X days or its more complicated setup?

There is a bit more to it because we have edge nodes in 10+ or so different datacenters. So a lot of the challenge is keeping the certs all synced up.

**Comment by jascodes** [comment]
I will be really greatful for temp fix for these. I have bunch of portfolio pages. That I have shared in last couple of days. It will be quite embarrassing if those don't open 😝. 

yobetit.jas.bio
fit3d.jas.bio
zettalabs.jas.bio
zenart.jas.bio
cv.jas.bio
dotnet.jas.bio
as3.jas.bio
ml.jas.bio

Thx 🙏 very much....

**Comment by jascodes** [comment]
Hey @sintaxi 

I have provided https links on my CV and interview couple of critical interviews are coming up in next couple of days. I just wanted to ask, if you think its easy fix or it will take time to resolve. 

Thx
Jas

**Comment by sintaxi** [comment]
Should be all set now. Please verify.

**Comment by jascodes** [comment]
Bro it looks like you allotted one by one ssl for each subdomain. Thanks very much for that. 🙏 

Anyways I guess the wildcard renewal might be complicated affair. 

Anyways thanks for your support.

**Comment by sintaxi** [comment]
You're welcome!

**Comment by jascodes** [comment]
Hey @sintaxi 

This issue seems to be happening again with https://zenart.jas.bio/

**Comment by sintaxi** [comment]
Fixed! If you hit me up on slack I'll show you how you can provision a cert yourself.

https://surge.sh/help/chat
