### ISSUE TITLE
you do not have permission to publish

### ISSUE THREAD

**Issue by baberibrar** [sintaxi/surge#415]
[](url)
![Annotation 2020-07-09 135936](https://user-images.githubusercontent.com/61284156/87022159-84f1b900-c1ef-11ea-8c0f-26bcbf9a3222.png)

**Comment by QmxiaoMengXin** [comment]
我也遇到了这个问题，请问你是怎么解决的

**Comment by baberibrar** [comment]
> 我也遇到了这个问题，请问你是怎么解决的

Please change the domain name, because your domain name already use

**Comment by kevnoutsawo** [comment]
> Please change the domain name, because your domain name already use

Thank you very much. I also had the same issue and I tried many obvious names. Now I tried a longer and more random one and it worked.
They should put a message that says it though.

**Comment by hamza-ali313** [comment]
thanks I am having the same problem

**Comment by gilbertl** [comment]
You just have to run and "enter" quickly. There's a race condition between you and everyone else in the world running surge. Someone else took the domain before you managed to secure it.

**Comment by MalvinJay** [comment]
Lmao! @gilbertl Thank you very much. You can imagine how quickly I was pressing the enter key 😅

**Comment by rosieswainson** [comment]
@gilbertl this was super helpful, thank you!!

**Comment by ola456** [comment]
Also had this issue, quickly pressing the enter key works - thanks! However found another solution as well, using the --domain flag, e.g. `surge --domain custom-name-nb83tptw3w.surge.sh`

**Comment by hrinka** [comment]
ARIGATO!!!

**Comment by maxim7137** [comment]
surge --domain maxim713-snake-0fae637fe0fc76bc-truculent-corn.surge.sh
Aborted - you do not have permission to publish to maxim713-snake-0fae637fe0fc76bc-truculent-corn.surge.sh

I use a unique domain, but it doesn't help.
What to do?

**Comment by siuson628** [comment]
> You just have to run and "enter" quickly. There's a race condition between you and everyone else in the world running surge. Someone else took the domain before you managed to secure it.

work... need very quickly...haha

**Comment by UncleClyde** [comment]
I had this issue. I prepended the automatically supplied URL with "1" and it worked. adding any alphanumeric as prepend will work.

**Comment by Fai2a** [comment]
Whats the issue when page are not found in surge?

**Comment by baberibrar** [comment]
> Whats the issue when page are not found in surge?

Please read this issue
https://github.com/sintaxi/surge/issues/179
