### ISSUE TITLE
Surge Webpage no longer loading, times out

### ISSUE THREAD

**Issue by JordanHoffman** [sintaxi/surge#418]
My website is no longer loading. It simply times out and it says it took too long to respond. This never happened before. I tried redeploying and it's still the same. It's at jordanhoffman.surge.sh

I live in South Florida and I don't know if this has to do with the servers Surge uses or what.

**Comment by sintaxi** [comment]
Thanks for reporting the issue. We had a DDOS attack which temporarily took down 3 of our data centers. This affected mostly projects with surge.sh domains. Projects appear to be back online now.
