### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by NathanNOSudo** [sintaxi/surge#423]
I have been unable to update a deployed surge.sh project. When I attempt to push changes to my surge.sh I get the following error:
Aborted - you do not have permission to publish to xxxxxxxxx.surge.sh. I think it has to do with an IP address issue but i am not sure.
Things I have tried so far:

- I tried every email I have
- Tried different machines
- I have tried different folders of the same project.
- I have checked surge version which I am on v0.21.6
- Every email I logged in with I have ran surge --list to see what I have access to but none show my deployed site.

Any suggestions or help would be greatly appreciated! Thanks in advance!

**Comment by sintaxi** [comment]
Send an email to support@surge.sh using the email address you used to sign up with on surge and we will look into it for you.
