### ISSUE TITLE
Surge 504 gateway time out

### ISSUE THREAD

**Issue by SNathJr** [sintaxi/surge#427]
It seems there is an outage in surge subdomains. I just created https://squashy-pico.surge.sh/ and it keeps responding with 504 gateway time out. Please look into it!

FYI: All previously created subdomains are down too (sometime with response 504 and other times with 408).

**Comment by sintaxi** [comment]
Thanks for reporting. 

We're under attack but we caught it quickly. Working on a solution now.

**Comment by sintaxi** [comment]
We believe we have mostly mitigated the attack (within the hour). 

Our system is still under very heavy load. We will continue to take steps to reduce the impact.

![Screen Shot 2020-10-12 at 1 51 00 AM](https://user-images.githubusercontent.com/867/95726961-6ce66700-0c2e-11eb-807d-fdfbfea1235b.png)

**Comment by SNathJr** [comment]
@sintaxi 
Thank you for the quick reply and resolution. I can confirm that old projects are live now. However, projects created during attack duration or any newly created project are not getting deployed. (they respond with 404 page not found).

**Comment by sintaxi** [comment]
@SNathJr I think everything should be resolved now. Thanks for reporting your findings. It helps a lot.

**Comment by SNathJr** [comment]
@sintaxi Thank you for replying! I can confirm that all of my projects are live now.

**Comment by sintaxi** [comment]
@SNathJr thanks. 

Here is a follow up graph. You can see what normal traffic looks like compared to the attack.

![Screen Shot 2020-10-12 at 10 36 40 AM](https://user-images.githubusercontent.com/867/95775260-f1f56e80-0c76-11eb-9d15-0ede7cb01e80.png)
