### ISSUE TITLE
deploy with single zip file

### ISSUE THREAD

**Issue by peratik** [sintaxi/surge#434]
Hi,

It would be very useful if you add deploy by single zip file.

Thank you

**Comment by chunkybanana** [comment]
Why? Just unzip and push to surge.

**Comment by peratik** [comment]
What if you have large files and slow internet connection!?

**Comment by sintaxi** [comment]
@peratik  Are you aware that surge currently does a tar and zip under the hood?

https://github.com/sintaxi/surge/blob/4007cda2e29acbddb6a712277a799471232c4271/lib/middleware/deploy.js#L339-L342

**Comment by sintaxi** [comment]
Closing this issue since this is effectively already covered by existing implementation.
