### ISSUE TITLE
My assets does not load once I upload my project to surge

### ISSUE THREAD

**Issue by udemezue01** [sintaxi/surge#435]
Hello, I am using vue js and I deployed a project with about three images in SVG format only to find out that they're all broken when they get to the surge server.
Here is a link to the project

http://travel-ly.surge.sh/

**Comment by sintaxi** [comment]
Hmm,  I’ll looks like your file names have capitals in them and the file
paths don't.

-b

**Comment by udemezue01** [comment]
Thanks, I fixed it already, I am grateful for this wonderful assistance
