### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Yusuf-shaik** [sintaxi/surge#436]
Servers seem to be down. I get an internal server error with my surge.sh projects, and the surge.sh official website is down as well.

**Comment by muzuiget** [comment]
Same to me:

```
# curl -i 'https://surge.sh'
HTTP/1.1 301 Moved Permanently
Server: SurgeCDN/1.4.0
Location: null://null/
Date: Sun, 31 Jan 2021 13:16:53 GMT
Connection: close
Content-Length: 27

Redirecting to null://null/
```

**Comment by Myssiry** [comment]
Same here

**Comment by sintaxi** [comment]
Thanks for reporting. It's all back up again.

Implemented a bug which wasn't caught by the automated tests and it went into production. All regions were temporarily out. Reverted back. 😓

**Comment by sintaxi** [comment]
I'm going to close this ticket now. This issue was addressed.
