### ISSUE TITLE
Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency

### ISSUE THREAD

**Issue by ItayNaveh** [sintaxi/surge#439]
node: 14.15.0
surge: 0.22.1

when i use surge it gives me this warning
`(node:2744) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency`
but it still works

**Comment by fu-sen** [comment]
It has happened before. I reported: https://github.com/sintaxi/surge/issues/403

The improved version of this issue does not have any issues. This is a temporary workaround:

```
npm i -g surge@0.21.7
```

ou can deploy even if a message is displayed.

**Comment by sintaxi** [comment]
I'm pretty sure this issue is resolved in edge which will be merged into master soon. You can test by running `npm install -g surge@edge`.

**Comment by fu-sen** [comment]
@sintaxi I'm trying it out with `npm install -g surge @ edge`. It's a good situation.
Furthermore, I got a nice present for me in Japan. 💻😲
I will try it immediately. I'm glad I kept using Surge! 😄

**Comment by sintaxi** [comment]
@fu-sen great! please report any issues you find.

**Comment by fu-sen** [comment]
I followed the npm package:
https://www.npmjs.com/package/surge

It happened again in `0.22.1` and did not happen in `0.22.0` .
This is the ideal workaround version for anyone who wants to use the official version.
```
npm i -g surge@0.22.0
```

However, since the package has been updated recently, I hope it will be improved in the next few days.

**Comment by sintaxi** [comment]
@fu-sen Its not clear to me what the problem is, and the difference between `v0.21.1` and `v0.22.0`. Can you elaborate? I think I may be missing the issue.

**Comment by fu-sen** [comment]
@sintaxi No, It is `v0.22.0` and `v0.22.1` . What have you changed recently during this time?

**Comment by sintaxi** [comment]
I was hoping to get more information from you :)

> It happened again in 0.22.1 and did not happen in 0.22.0 .

I'm very confused. What happened in `0.22.1` and did not happen in `0.22.0`? I want to help but I suspect you don't realize how unclear your report is.

I really appreciate you taking the time to report issues. To help I need stack traces, CLI output, and version numbers for both node & surge so I don't have to spend huge amounts of time trying to discover the problems you are already seeing.

**Comment by fu-sen** [comment]
Oh, I'm more into the `geo` response changing from` sgp` to `nrt`. 💻😆

**Comment by sintaxi** [comment]
resolved #448

**Comment by fu-sen** [comment]
@sintaxi good job! 👍

I have confirmed that the `surge` CLI has been updated and this bug is gone:
https://www.npmjs.com/package/surge?activeTab=versions

You need to update:
```
npm i -g surge
```

```
PS C:\Users\balloon> npm i -g surge
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

removed 7 packages, changed 112 packages, and audited 113 packages in 2m

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\balloon> surge --version

   v0.23.0

PS C:\Users\balloon> surge --help

  surge – single command web publishing. (v0.23.0)

  Usage:
    surge <project> <domain>

  Options:
    -a, --add           adds user to list of collaborators (email address)
    -r, --remove        removes user from list of collaborators (email address)
    -V, --version       show the version number
    -h, --help          show this help message

  Additional commands:
    surge whoami        show who you are logged in as
    surge logout        expire local token
    surge login         only performs authentication step
    surge list          list all domains you have access to
    surge teardown      tear down a published project
    surge plan          set account plan

  Guides:
    Getting started     surge.sh/help/getting-started-with-surge
    Custom domains      surge.sh/help/adding-a-custom-domain
    Additional help     surge.sh/help

  When in doubt, run surge from within your project directory.

PS C:\Users\balloon>▄
```

**Comment by sintaxi** [comment]
@fu-sen thanks for confirming!

**Comment by usmanhashmis** [comment]
![image](https://user-images.githubusercontent.com/55950977/160250228-eacd0f95-d242-483e-9872-12ebf5c25fe8.png)
how to resolve?

**Comment by sintaxi** [comment]
@usmanhashmis how is that related to surge?
