### ISSUE TITLE
Add Discussions to this project

### ISSUE THREAD

**Issue by fu-sen** [sintaxi/surge#441]
Surge has Twitter and Slack, but no forums.
As a result, this issue became dirty with many rudimentary questions.

So why add Discussions to this project? It's a new feature added by GitHub in 2020.
https://docs.github.com/en/discussions

It encourages interaction between Surge users and allows them to share ideas on how to use them and suggestions for new features. The developer does not have to handle everything. and you can limit this Issues to a true bug reporter.

**Comment by sintaxi** [comment]
Agreed. Do you happen to know of another project that does this well?

**Comment by fu-sen** [comment]
A project I'm working on with this implementation:
https://github.com/vercel/vercel/discussions

... yes. It is a rival (now.sh) that was initially compared side-by-side with Surge. So I didn't put this in.

**Comment by fu-sen** [comment]
I've recently figured you're active and trying to bring new features to Surge.
Actually, it should be issued separately, but I will put it here.

You should consider making Surge a Github organization.
Surely it will help you in your work and add friends team in the future.

This user hasn't been active lately:
https://github.com/surge

Ask the GitHub staff. This account may be released.
https://support.github.com/request

If that account doesn't work, you could consider something like `surge-sh` instead.

**Comment by fu-sen** [comment]
Yeah, I confirmed:
https://github.com/sintaxi/surge/discussions

We hope this will make this issue an ideal place. I'm good enough to close this.
