### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by catdrout420** [sintaxi/surge#452]
I cant deploy! This is my output:

┌──(catdrout㉿localhost)-[~/Рабочий стол/website/src]
└─$ surge                       

   Running as catdrout@tutanota.de (Student)

        project: /home/catdrout/Рабочий стол/website/src/
         domain: 7catdrout.xyz

   Aborted - you do not have permission to publish to 7catdrout.xyz

      please help! 7catdrout.xyz is my domain

**Comment by sintaxi** [comment]
run `surge whoami` and make sure your authenticated as the same user that published the site.

**Comment by catdrout420** [comment]
I mean. That account is my old account that i dont have acess to. I can verify my that i own the domain (7catdrout.xyz) by creating a TXT record.

**Comment by catdrout420** [comment]
![Screenshot_20210523_155758](https://user-images.githubusercontent.com/81867095/119267826-b6912a00-bbdf-11eb-9c8b-9c6756f9e781.png)
Proof

**Comment by catdrout420** [comment]
# This is my proof
![Screenshot_20210523_155853](https://user-images.githubusercontent.com/81867095/119267847-d4f72580-bbdf-11eb-9d17-21e2c9a02515.png)

**Comment by sintaxi** [comment]
Email support@surge.sh with your request and we will walk you through a domain verification process.
