### ISSUE TITLE
Getting 410 gone error

### ISSUE THREAD

**Issue by technikhil314** [sintaxi/surge#453]
I have my site deployed on surge. But all of a sudden it has started giving http 410. Anybody know what is the reason for this?

**Comment by sintaxi** [comment]
Your account has likely been flagged for abuse. Review the [Surge Terms of Service](https://surge.sh/terms) and if you think a mistake has been made send an email to support@surge.sh with as much details as you can provide.

**Comment by technikhil314** [comment]
@sintaxi May I know what all details should I share?

**Comment by sintaxi** [comment]
I suggest listing all the accounts you have on surge (by email address) and all the project you have published (by domain).
