### ISSUE TITLE
Surge list not working

### ISSUE THREAD

**Issue by samwelkinuthia** [sintaxi/surge#455]
I get the following error:

TypeError: Cannot read property 'grey' of undefined

![Screenshot from 2021-06-13 14-40-05](https://user-images.githubusercontent.com/27720313/121805792-58db8500-cc55-11eb-9e03-3b20417456a5.png)

**Comment by samwelkinuthia** [comment]
The issue is specific to version 0.23.0 and is not present in version 0.22.0

**Comment by sintaxi** [comment]
@samwelkinuthia I can fix this for you I just need your surge email address. Can you send this information to support@surge.sh?

thanks.

**Comment by samwelkinuthia** [comment]
Working now, thank you.
