### ISSUE TITLE
Are HTTP redirects possible?

### ISSUE THREAD

**Issue by crtr0** [sintaxi/surge#46]
I know I can do a redirect on the client-side with META, but I'm curious if this is (will be) possible with Surge. It's something that GH pages definitely doesn't support.

**Comment by sintaxi** [comment]
I have this prototyped somewhere but it never landed. Definitely would be a great addition to surge. Let me look into it.

**Comment by davidhund** [comment]
+1

I just learned of the `200.html` catch-all trick (neat!) but would *love* to be able to have more control over custom redirects and *rewrites*. This would, for example, allow us to implement 'Pragmatic Touch Icons': https://gist.github.com/davidhund/332316f82440ef4377f3

```
RewriteRule ^apple-touch-icon(.*).png$ apple-touch-icon.png [L]
```

I understand you cannot support `.htaccess` and I can see this being out of scope for a CDN-with-extra' but one can dream ;-)

**Comment by kennethormandy** [comment]
Hey @crtr0, @davidhund, and any future people reading this!

[Custom redirects are now supported](https://surge.sh/help/adding-redirects) as part of [Surge Plus](https://surge.sh/pricing). Just add a `ROUTER` file into the root of your project. Then, you can specify a new redirect on each line. For example, to redirect `/contact` to `/about`, you would add:

```
301     /contact     /about
```

You can also specify :checkered_flag: patterns. Here’s how you might redirect and old WordPress blog to your new static site:

```
301   /:year/:month/:day/:slug   /blog/:slug
``` 

Let us know if you have any questions or feedback. More details are in the :bookmark_tabs: [redirects help article](https://surge.sh/help/adding-redirects). Thanks so much for using Surge!

**Comment by davidhund** [comment]
Awesome stuff, thanks @kennethormandy!
