### ISSUE TITLE
Error - Deployment did not succeed

### ISSUE THREAD

**Issue by xiaohk** [sintaxi/surge#461]
Hello, I am a huge fan of surge!

I encountered this error message today: `Error - Deployment did not succeed` when I tried to deploy my project to a `surge.sh` domain. It happens to different `surge.sh` domains (both `http` or `https`).

Does that mean there are some issues on the surge server, or should I deploy it differently?

Thanks!

**Comment by Ardouz11** [comment]
i have the same problem `
Error: aborted
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.socketCloseListener (node:_http_client:462:19)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7) {
  code: 'ECONNRESET'
}
Error - Deployment did not succeed.`
any suggestions?

**Comment by techterbium** [comment]
I am seeing this very same problem. Any pointers please?

**Comment by GedeonWest** [comment]
Same problem

**Comment by ColemanMaximus** [comment]
Just now had this happen to me, and seeing a few others having the issue around the same time, perhaps it's a surge issue and not our config.

**Comment by sintaxi** [comment]
Old ticket. Issue resolved. Closing.
