### ISSUE TITLE
Expired SSL Certificates

### ISSUE THREAD

**Issue by alexandrenicol** [sintaxi/surge#474]
Just a quick message as I’m doing a bit of support for a charity based UK. 

They have a website that’s hosted using Surge, their subdomain is “[account-name].surge.sh”, and it’s critical to running their services properly. 

Since yesterday, they haven’t been able to access the service because the SSL certificate associated to the domain appears to have expired. Whilst checking, I have also checked surge.sh and it appears to be expired as well. 

I was wondering if that was something you were aware of?

**Comment by 9oelM** [comment]
Same here. Even the root domain (surge.sh) would show the same thing. Is Surge going down?
![image](https://user-images.githubusercontent.com/22465806/165870354-aa754910-5434-4c5e-9ae1-340e7b361208.png)

**Comment by DannyvanderJagt** [comment]
@sintaxi Any updates on this? We're using surge at the company and it's having an impact. If it isn't fixed quickly (today/monday) we will need to switch to another service

**Comment by dedmondson39** [comment]
Same here. UK based.
The Issue seems sporadic as each request may or may not have a valid SSL certificate. For failure the certificate is shown to have expired on the 27th April 2022

**Comment by alexandrenicol** [comment]
(Author) Closing this because it seems to have been resolved, even though I haven't had any communications from the people behind Surge (here or via emails).

<img width="636" alt="Screenshot 2022-05-03 145019" src="https://user-images.githubusercontent.com/6968775/166465770-10d929aa-503f-482a-bd91-472fcd831a25.png">
