### ISSUE TITLE
Loading module from “https://svelte-spectre.surge.sh/__data.js?__invalid=y&__id=2” was blocked because of a disallowed MIME type (“text/html”).

### ISSUE THREAD

**Issue by Valexr** [sintaxi/surge#479]
Loading module from “https://svelte-spectre.surge.sh/__data.js?__invalid=y&__id=2” was blocked because of a disallowed MIME type (“text/html”).

**Comment by sintaxi** [comment]
IIRC surge omits files beginning with underscore by default. If you create a `.surgeignore` file you should be whitelist that file.

**Comment by Valexr** [comment]
> IIRC surge omits files beginning with underscore by default. If you create a `.surgeignore` file you should be whitelist that file.

Just file name, not searchParams?

**Comment by Valexr** [comment]
& why they omitted ?

**Comment by Valexr** [comment]
Fixed with right build config 👍🏻 surge it's 👌🏻

**Comment by sintaxi** [comment]
@Valexr great!

The default underscore omission was derived from conventions that some SSGs (mainly harp) and other publishing platforms have. In many situation sensitive or configuration information is stored in files that begin with underscore. Harp uses this convention heavily.
