### ISSUE TITLE
503 Service Unavailable No server is available to handle this request.

### ISSUE THREAD

**Issue by LucasMW** [sintaxi/surge#483]
```
503 Service Unavailable
No server is available to handle this request.
```

When I try to view it, it is there.
When people from other countries, or me with vpn, we get this message.

Happened today, after I updated the site. Has never happened before.

This is the site: https://headache.surge.sh/

This is the page that won't load https://headache.surge.sh/test.html

**Comment by jeffreybrowning** [comment]
Happening for me today.
