### ISSUE TITLE
DNS commands not working

### ISSUE THREAD

**Issue by hubbyist** [sintaxi/surge#494]
I am unable to change dns records. Also I have to remove all dns records. But there is no working option it seems.

```
~$ surge dns example.com

   Running as example@gmail.com (Student)

   Aborted - No such file or directory: dns
```

**Comment by mster81** [comment]
I don't think 'dns' is a valid command.. 

Also, DNS is not a function of surge as it is your DNS providor who will set / remove DNS records and or cNames, a records etc. 

I'm no expert here but my understanding is surge simply providing you their cName, when you publish to surge its creating that domain mapping across thier clusters so when the request comes in with that header it knows where to map the project. 

If you need to remove a project from surge then probably want the teardown command

**Comment by hubbyist** [comment]
Even after teardown surge is still suppliying my domain as not found. And when I ping I get the IP of the surge server not my domain name provider or cloudflare that I use as DNS server.

**Comment by mster81** [comment]
I don't understand the question here.. 

1) Teardown will remove the project (so remove files, domain mapping etc [My assumption])
2) Not sure I understand what you mean by ping? What are you pinging, your domain? 

Assuming you pinged your domain, and its coming back to 'surge' servers, and you have removed the surge cName from the DNS provider then it could just be DNS propagation. It can take time for them to update. Also, you could try to change the TTL on your DNS host, ensure any CDN is flushed, even your local DNS flush can help, is only to test locally.

**Comment by hubbyist** [comment]
When I write "https://mydomain.com" I am getting "project not found powered by [surge.sh](https://surge.sh/)" page. Is this normal? My A records seems to be showing 104.21.78.73, 172.67.217.221 as IP address for my domain.

**Comment by hubbyist** [comment]
All seems to be about DNS caching and propogation related problems. Sorry for the false alarm again.
