### ISSUE TITLE
Error on entering subdomain

### ISSUE THREAD

**Issue by kennethormandy** [sintaxi/surge#5]
If you include the `.surge.sh` as part of the domain, you get an error.

```
             domain: (slow-gun.surge.sh) firsthand.surge.sh
             upload:
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
```

__Edit__ Actually, that wasn’t what it was, I am unclear on why I got that error.

**Comment by silentrob** [comment]
I can't reproduce this. Is it still valid?

**Comment by kennethormandy** [comment]
I left I pretty useless update note:

> Edit Actually, that wasn’t what it was, I am unclear on why I got that error.

So…let’s say it was probably a duplicate of #12.
