### ISSUE TITLE
If a directory contains a less file with an unresolvable @reference, surge fails quietly

### ISSUE THREAD

**Issue by davidascher** [sintaxi/surge#50]
as demonstrated live =)

**Comment by davidascher** [comment]
https://www.dropbox.com/s/ubudfixddmhqvkq/build.zip?dl=0 for a (far from reduced) test case

**Comment by davidascher** [comment]
(renaming bundle.less to bundle.css makes this directory display well when hosted by surge)

**Comment by sintaxi** [comment]
Thanks for filing this issue. This is now resolved. this app now works as is. :)
