### ISSUE TITLE
Someone uploaded a spam site to my domain

### ISSUE THREAD

**Issue by jeanmenezes** [sintaxi/surge#502]
Hello, I am contacting you via github issues because the chat in your website is down.

Somebody somehow managed to post a spam website to my custom domain, which DNS records were correctly pointed to surge.
I have a functioning surge site in a subdomain, but the top domain in my site was hijacked by some other surge account and now I can't either publish my own content to it nor teardown the spam site.
If you want to check the issue closely, you can PM me or provide an email address that I can use to provide more info in private. I can provide my account credentials and registered domain as proof of my issue.

Thanks in advance!

**Comment by sintaxi** [comment]
Oh no! Please email support@surge.sh and we will deal with this right away.

thanks,
Brock

**Comment by jeanmenezes** [comment]
Thanks a lot. Email sent.

Em seg., 10 de abr. de 2023 19:11, Brock Whitten ***@***.***>
escreveu:
