### ISSUE TITLE
Deployment broken

### ISSUE THREAD

**Issue by johntringham** [sintaxi/surge#515]
Steps to replicate:

Deploy or redeploy any surge project via the surge command line

Expected: it deploys and you can access it in a browser soon after

Actual: The command line tool says it deployed successfully, but the url it deploys to displays "project not found". This is happening with new projects and previously existing ones that are being redeployed

Example affected site: https://shiny-disease.surge.sh/ - this was deployed a few minutes ago. It's just a very basic index.html file, but it's displaying as "project not found", despite the surge cli saying it was successfully deployed.

This bug was mentioned in a comment here: https://github.com/sintaxi/surge/issues/514#issuecomment-1855283693 - which is presumably a related issue due to the timings

**Comment by marclucraft** [comment]
I see a 404 for my latest deployment too, but It's not just on deployment – list throws an error too.

<img width="819" alt="image" src="https://github.com/sintaxi/surge/assets/3025406/417664b2-335d-4135-8937-c057db3674ae">

**Comment by johntringham** [comment]
@marclucraft Yeah I'm seeing this error from `surge list` as well - that issue was reported earlier over here: https://github.com/sintaxi/surge/issues/514 . Hopefully both issues have the same root cause and can be fixed together, but I wanted to log this separately as it feels like the bigger overall problem

**Comment by tadayosi** [comment]
@marclucraft You can manually patch `list.js` something like this to get around the list issue for the time being.
```js
        var row = [
          perm || project.domain,
          project.timeAgoInWords?.grey,
          project.cmd?.grey,
          project.platform?.grey,
          pn || "",
          //lastcmd !== project.cmd ? (project.cmd).grey : "",
        ]
```

**Comment by elgatito** [comment]
> @marclucraft You can manually patch `list.js` something like this to get around the list issue for the time being.
> 
> ```js
>         var row = [
>           perm || project.domain,
>           project.timeAgoInWords?.grey,
>           project.cmd?.grey,
>           project.platform?.grey,
>           pn || "",
>           //lastcmd !== project.cmd ? (project.cmd).grey : "",
>         ]
> ```

This change fixes issue with `surge list` but not with getting `Project not found` after making deployment.

**Comment by marclucraft** [comment]
Appreciated @elgatito! Although, my main concern is deployment. Hope a fix can be found soon.

**Comment by sintaxi** [comment]
Hey all, Brock from surge here.  Definitely there is an issue. Looking into it. Thanks for reporting.

**Comment by johntringham** [comment]
I've just retested on https://shiny-disease.surge.sh/ and another surge subdomain - it's back up and deploying successfully from what I can see. @sintaxi thanks for looking into it - any chance of a debrief/update on what caused the problem? I won't close this issue just yet in case the problem is still ongoing

**Comment by sintaxi** [comment]
Old ticket. Issue resolved. closing.
