### ISSUE TITLE
How

### ISSUE THREAD

**Issue by LegitTalon** [sintaxi/surge#52]
I would like to know.

**Comment by silentrob** [comment]
npm install surge -g

**Comment by LegitTalon** [comment]
I admit that my question was ambiguous. I would like to know how this can be run free of cost to the users.

**Comment by silentrob** [comment]
Our plan is to create a paid tier at some point, however we didn't want to do that with arbitrary constraints, we wanted to focus on creating actual value today and seeing what the community needs next, and where we can add more value later. 

I hope that answers your question, and I believe the goal is to always have a free tier. Simular to Github Pages.
