### ISSUE TITLE
all my surge websites are down

### ISSUE THREAD

**Issue by Preston-Riley** [sintaxi/surge#522]
please help

**Comment by kaijudev** [comment]
Same, I sent an email off to them - hopefully this gets resolved quickly.

**Comment by sintaxi** [comment]
Confirm there is a problem. Issue not obvious. Taking a look and reaching out to our upstream providers.

**Comment by alexgleason** [comment]
Looks like it's still happening

**Comment by sintaxi** [comment]
We spun up new hardware on the weekend. Will be cutting the traffic over shortly.

-B
