### ISSUE TITLE
Unable to update site

### ISSUE THREAD

**Issue by sseeaann** [sintaxi/surge#530]
I am unable to see published updates reflected on my site. I was attempting to make updates but didn't see any changes so I went nuclear and published an update with no files within the folder. The site accept that action and now reflects the 404 error since there's no content published. However, I cannot publish an update with the content moved back into the folder. **TLDR/What works:** Publishing to a brand new domain accepts the initial push, but subsequent updates are not reflected. This issue is a newer one as I had no problems making updates within the last month or two.

**Comment by krau5** [comment]
Same

**Comment by sintaxi** [comment]
can you please run `ping <your-domain>` and show me the output?

**Comment by krau5** [comment]
Hi @sintaxi 👋🏻 
```
PING <my-domain>.surge.sh (138.68.112.220): 56 data bytes
64 bytes from 138.68.112.220: icmp_seq=0 ttl=53 time=28.885 ms
64 bytes from 138.68.112.220: icmp_seq=1 ttl=53 time=38.743 ms
64 bytes from 138.68.112.220: icmp_seq=2 ttl=53 time=33.427 ms
64 bytes from 138.68.112.220: icmp_seq=3 ttl=53 time=33.233 ms
64 bytes from 138.68.112.220: icmp_seq=4 ttl=53 time=25.500 ms
64 bytes from 138.68.112.220: icmp_seq=5 ttl=53 time=33.127 ms
64 bytes from 138.68.112.220: icmp_seq=6 ttl=53 time=29.343 ms
64 bytes from 138.68.112.220: icmp_seq=7 ttl=53 time=25.685 ms
64 bytes from 138.68.112.220: icmp_seq=8 ttl=53 time=25.643 ms
64 bytes from 138.68.112.220: icmp_seq=9 ttl=53 time=31.400 ms
64 bytes from 138.68.112.220: icmp_seq=10 ttl=53 time=30.702 ms
64 bytes from 138.68.112.220: icmp_seq=11 ttl=53 time=25.068 ms
64 bytes from 138.68.112.220: icmp_seq=12 ttl=53 time=33.325 ms
64 bytes from 138.68.112.220: icmp_seq=13 ttl=53 time=24.939 ms
64 bytes from 138.68.112.220: icmp_seq=14 ttl=53 time=33.783 ms
64 bytes from 138.68.112.220: icmp_seq=15 ttl=53 time=25.153 ms
64 bytes from 138.68.112.220: icmp_seq=16 ttl=53 time=31.173 ms
64 bytes from 138.68.112.220: icmp_seq=17 ttl=53 time=33.405 ms
```

**Comment by sseeaann** [comment]
PING shippie.surge.sh (138.197.235.123): 56 data bytes
64 bytes from 138.197.235.123: icmp_seq=0 ttl=47 time=39.545 ms
64 bytes from 138.197.235.123: icmp_seq=1 ttl=47 time=36.854 ms
64 bytes from 138.197.235.123: icmp_seq=2 ttl=47 time=34.681 ms
64 bytes from 138.197.235.123: icmp_seq=3 ttl=47 time=34.555 ms
64 bytes from 138.197.235.123: icmp_seq=4 ttl=47 time=36.056 ms
64 bytes from 138.197.235.123: icmp_seq=5 ttl=47 time=43.126 ms
64 bytes from 138.197.235.123: icmp_seq=6 ttl=47 time=34.513 ms
64 bytes from 138.197.235.123: icmp_seq=7 ttl=47 time=34.323 ms
64 bytes from 138.197.235.123: icmp_seq=8 ttl=47 time=45.548 ms
64 bytes from 138.197.235.123: icmp_seq=9 ttl=47 time=33.355 ms
64 bytes from 138.197.235.123: icmp_seq=10 ttl=47 time=33.724 ms
64 bytes from 138.197.235.123: icmp_seq=11 ttl=47 time=91.396 ms
64 bytes from 138.197.235.123: icmp_seq=12 ttl=47 time=34.646 ms
64 bytes from 138.197.235.123: icmp_seq=13 ttl=47 time=37.327 ms
64 bytes from 138.197.235.123: icmp_seq=14 ttl=47 time=33.894 ms
64 bytes from 138.197.235.123: icmp_seq=15 ttl=47 time=33.610 ms
64 bytes from 138.197.235.123: icmp_seq=16 ttl=47 time=38.576 ms
64 bytes from 138.197.235.123: icmp_seq=17 ttl=47 time=37.775 ms

**Comment by sintaxi** [comment]
Thanks for providing this information (and closing the ticket). We believe this issue is now cleared up.
