### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by kookywarrior** [sintaxi/surge#532]
Why am I getting this error when deploying
Error - Deployment did not succeed.

**Comment by sseeaann** [comment]
Same experience for me as well. In relation to [Issue 530](https://github.com/sintaxi/surge/issues/530), yesterday I was able to update my site **but only** if I made HTML changes, meaning that any of my JS updates wouldn't take until I modified the visual elements such as HTML or CSS. Even then, I had to frequently push updates multiple times until the site reflected the changes.

Today, I receive only the error in my command line.

**Comment by kookywarrior** [comment]
Also I can't seem to login / create a new account

**Comment by sintaxi** [comment]
Thanks for the report. We had a saturated disk on one of our deployment servers. Issue is now resolved.

**Comment by eliseodedios** [comment]
We continue to have problems implementing and updating our websites.
