### ISSUE TITLE
503 Service Unavailable on sites with custom domain

### ISSUE THREAD

**Issue by r4dian** [sintaxi/surge#536]
Sites with custom domains are down with the error as in title

Sites with {whatever}.surge.sh domains are working normally.

**Comment by r4dian** [comment]
If this is a clue, pinging both my sites with custom domains gets a reply like
`64 bytes from 45.55.110.124 (45.55.110.124): icmp_seq=1 ttl=128 time=149 ms`
while pinging the sites on surge.sh get a different ip responding. ( e.g. 188.166.132.94 or 138.68.112.220 )

**Comment by lisaMcwilliams** [comment]
I am having the same issue:
PING seenventures.co (172.67.131.139): 56 data bytes
64 bytes from 172.67.131.139: icmp_seq=0 ttl=57 time=12.205 ms
64 bytes from 172.67.131.139: icmp_seq=1 ttl=57 time=14.284 ms
64 bytes from 172.67.131.139: icmp_seq=2 ttl=57 time=18.912 ms
64 bytes from 172.67.131.139: icmp_seq=3 ttl=57 time=17.539 ms
64 bytes from 172.67.131.139: icmp_seq=4 ttl=57 time=14.631 ms
64 bytes from 172.67.131.139: icmp_seq=5 ttl=57 time=17.268 ms
64 bytes from 172.67.131.139: icmp_seq=6 ttl=57 time=15.807 ms
64 bytes from 172.67.131.139: icmp_seq=7 ttl=57 time=16.256 ms

**Comment by r4dian** [comment]
They recovered after a couple of hours.
