### ISSUE TITLE
NPM install: node-waf and zlib errors, error 127 (+ deprecated NPM packages)

### ISSUE THREAD

**Issue by MrPiggy105** [sintaxi/surge#537]
This issue seems to have happened overnight, on both a scheduled GitHub Action and my Fedora machine at home.

When I try to install Surge globally with NPM, it warns that several dependencies are deprecated, and something has seemingly broken the install overnight:

```
❯ npm install -g surge
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated fstream@1.0.12: This package is no longer supported.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm error code 127
npm error path /home/MYNAME/.nvm/versions/node/v21.6.2/lib/node_modules/surge/node_modules/zlib
npm error command failed
npm error command sh -c node-waf clean || true; node-waf configure build
npm error sh: line 1: node-waf: command not found
npm error sh: line 1: node-waf: command not found
npm error A complete log of this run can be found in: /home/MYNAME/.npm/_logs/2024-08-11T01_26_15_869Z-debug-0.log
```

Same goes for the GitHub Action, which then ends the scheduled workflow:

```
Run npm install -g surge
  npm install -g surge
  shell: /usr/bin/bash -e {0}
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated fstream@1.0.12: This package is no longer supported.
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm error code 127
npm error path /usr/local/lib/node_modules/surge/node_modules/zlib
npm error command failed
npm error command sh -c node-waf clean || true; node-waf configure build
npm error sh: 1: node-waf: not found
npm error sh: 1: node-waf: not found

npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-08-11T01_18_07_846Z-debug-0.log
Error: Process completed with exit code 127.
```

At the previous Actions workflow run (about 12hrs before posting this), the dependencies also appear deprecated, but don't result in an error:
```
Run npm install -g surge
  npm install -g surge
  shell: /usr/bin/bash -e {0}
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated fstream@1.0.12: This package is no longer supported.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 112 packages in 4s

4 packages are looking for funding
  run `npm fund` for details
```

**To be clear (didn't realise until finished writing this), it may not necessarily be the deprecated packages causing the error. Both outputs seem to fail to use zlib, then they try to run `sh -c node-waf clean || true; node-waf configure build` which fails too because node-waf does not exist. I'm not sure what it's trying to do.**

Thanks for your help in advance! Curious if anyone else is having this problem

**Comment by sintaxi** [comment]
Hey, thanks for reporting. What version of node are you running?

**Comment by MrPiggy105** [comment]
Thank you for your help, 
I am not completely sure about my own machine, but the setup-node@v4 action is using this environment configuration by default:
  node: v18.20.4
  npm: 10.7.0
  yarn: 1.22.22

I will update this when I have access to my Fedora laptop.

**Comment by afc163** [comment]
Run into same error here: https://github.com/ant-design/ant-design/actions/runs/10338172234/job/28615907557

**Comment by Cleshz** [comment]
Experiencing the same issue here😭

**Comment by sintaxi** [comment]
A quick temporary fix should be to specify a previous version (v0.23.1) of surge...

change the following...
https://github.com/ant-design/ant-design/blob/master/.github/workflows/preview-deploy.yml#L97C11-L97C92

to...
```
npx surge@0.23.1 --project ./ --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}
```

**Comment by Cleshz** [comment]
ye the 0.23.1 works. thanks😁

**Comment by MrPiggy105** [comment]
Thanks for this :) Probably a busy day patching 0.24. Guess this means it was introduced in the new 0.24 update this morning? (AEST)

From the error and some StackOverflow and Google I think node-zlib (or just zlib) hasn't been updated in 13 years although there is built-in support for zlib from Node, and that old package was using node-waf, which has also been deprecated and replaced with node-gyp. Something broke in the new surge versions & now it's trying to run node-waf. 

On the other hand, I have no idea what I'm talking about.
Thanks for maintaining Surge! Good luck

**Comment by j-e-clark** [comment]
Hi,

Just to add I have the same issues with:
node: v20.16.0
npm: 10.8.2

Thanks

**Comment by sintaxi** [comment]
Really appreciate all your reports! 

`surge@0.24.6` is shipped which patches this error. Please let me know if you still see this issue. It turns out a super old version of `zlib` was being installed instead of using the `zlib` that is built into nodejs. Thanks @MrPiggy105 for the heads up!

I am aware surge still has some dependencies that are a bit long in the tooth. I plan on addressing this.

**I will close this issue once confirmed working by some of you.**

**Comment by liunnn1994** [comment]
Works for me in [docker:24](https://hub.docker.com/layers/library/docker/24/images/sha256-167bad11bade46d4d9a88646ed7f9b11014dfdb898ba75c5a390eb03f21f0c45?context=explore)
```
node v20.15.1
npm 10.8.0
pnpm 9.7.0
surge v0.24.6
```

**Comment by MrPiggy105** [comment]
Can confirm this patch works. Thanks for your help! No rush to fix those deps
