### ISSUE TITLE
Exit during path prompt

### ISSUE THREAD

**Issue by cfjedimaster** [sintaxi/surge#54]
If you exit surge during the path prompt, you get an error:

/usr/local/lib/node_modules/surge/lib/middleware/project.js:36
          result.project == "./"
                ^
TypeError: Cannot read property 'project' of undefined

**Comment by brandonb927** [comment]
Came here to echo this issue as well.

**Comment by kennethormandy** [comment]
This got fixed a little while back but we forgot to close the issue. Thanks for reporting!

![out](https://cloud.githubusercontent.com/assets/1581276/7920547/b3da4890-0854-11e5-959e-be71268edc23.gif)
