### ISSUE TITLE
503 error from Singapore

### ISSUE THREAD

**Issue by xris-r** [sintaxi/surge#546]
I created a new site, and initially got 503 errors whenever I entered the specified URL into the browser.  

Eventually I found that I _could_ see my web pages -- if I bypassed DNS and specified a different mirror.  I tried all 10 of your mirrors, and only the one in Singapore (139.59.195.30) returned a 503 error.  All others returned 200.

This issue has persisted since Friday (2 days ago), when I first created the site.

This demonstrates the problem:
```
mirrors=(sfo lhr yyz jfk ams fra sgp blr syd nrt)
for mirror in ${mirrors[@]}; do echo -n $mirror ' '; curl -H "Host: longing-ray.surge.sh" --write-out '%{http_code}\n' -o /dev/null --silent ${mirror}.surge.sh; done
sfo  200
lhr  200
yyz  200
jfk  200
ams  200
fra  200
sgp  503
blr  200
syd  200
nrt  200

```

**Comment by fu-sen** [comment]
'm from Japan but it still seems to be choosing the Singapore server and I'm getting a 503.

```
$ dig example.surge.sh
;; ANSWER SECTION:
example.surge.sh.       301     IN      A       139.59.195.30
```

https://gist.github.com/sintaxi/670654550d4b30354614c7cfb72d5bf5#file-regions-txt-L10

```
$ curl --head  example.surge.sh
HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html
```

**Comment by fu-sen** [comment]
Yes, that would be correct in the context of this report.

```
$ curl --head -H "Host: example.surge.sh" yyz.surge.sh
HTTP/1.1 404 Not Found
Server: Surge
Surge-Cache: HIT
Surge-Stamp: 10330
Content-Type: text/html; charset=utf-8
Content-Length: 8253
ETag: W/"203d-BDTTsPJbGhhTleluWqeLfoLxZdI"
Date: Mon, 04 Nov 2024 02:31:22 GMT
Connection: close
```

```
$ curl --head -H "Host: example.surge.sh" sgp.surge.sh
HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

**Comment by xris-r** [comment]
Agreed - it is all fine now.  Thanks.

**Comment by fu-sen** [comment]
Because I noticed on reopen. the Singapore server `sgp.surge.sh` is returning `503` again.

```
$ curl --head sgp.surge.sh
HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html
```

Everything is working fine except for `sgp.surge.sh` .

```
$ curl --head lhr.surge.sh
HTTP/1.1 200 OK
Server: Surge
Surge-Cache: HIT
Surge-Stamp: 10974::1582968049245
Content-Type: text/html; charset=utf-8
Content-Length: 8231
ETag: W/"2027-BQoKqAyxjDJ7oB9ej5Pjm2UmBT0"
Date: Thu, 07 Nov 2024 23:25:21 GMT
Connection: close
```

**Comment by xris-r** [comment]
I think the issue with Singapore is fixed.

**Comment by fu-sen** [comment]
Yep, there are no more servers returning 503 now.

**Comment by mulleydev** [comment]
Singapore is down with many others


sfo  504
lhr  200
yyz  504
jfk  504
ams  504
fra  504
sgp  504
blr  504
syd  504
nrt  504
