### ISSUE TITLE
Persistent ETIMEDOUT Error during Surge Login after Deployment Failure

### ISSUE THREAD

**Issue by hsulijen** [sintaxi/surge#549]
### Description
I am encountering a persistent ETIMEDOUT error when attempting to log in to Surge. This happens every time I input my email and password during surge login.

### Steps to Reproduce
These are the steps I followed, and the issue consistently occurred in my environment:
1. Run `surge login` in the terminal. Any command related to surge (e.g., `surge`, `surge -v`, `surge whoami`, `surge --clear`, `surge list`, `surge --no-auth`, `surge --reset`) will lead to the terminal requiring login information.
2. Input email and password as prompted.
3. Encounter the timeout error after a short delay.

### Error Message
```bash
PS [[my project directory]] > surge login

   Login or create surge account by entering email & password.

          email: (node:6192) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

          email: [[my email]]
       password:                                                                                                                                                     
C:\Users\rayh1\AppData\Roaming\npm\node_modules\surge\lib\util\helpers.js:203
      if (e) throw e
             ^

Error: connect ETIMEDOUT 192.241.214.148:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.241.214.148',
  port: 443
}

Node.js v22.12.0
```

### Version Information
Version Information
```bash
PS [[my project directory]] > nvm -v
>> node -v
1.1.12
v22.12.0
```
```bash
PS [[my project directory]] > surge -v

   Welcome to surge! (surge.sh)
   Login or create surge account by entering email & password.

          email: (node:8416) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


   Aborted - Not authenticated.

```

### System Information

```bash
- OS Name: Microsoft Windows 11 Home
- OS Version: 10.0.22631 N/A Build 22631
- Processor: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2400 MHz
- Network Card: Realtek RTL8822CE 802.11ac PCIe Adapter (Wi-Fi)
```

### Additional Notes

1. The issue started after an unsuccessful deployment, possibly related to a corrupted session or network configuration.
2. I have tried the following, but none of them worked. 
- Reinstalling Surge.
- Changing Node.js versions.
- Switching networks (e.g., mobile hotspot).
- Disabling the firewall.
3. I am new to Surge and IT tools in general, so I might have overlooked something.

### My Questions
1. What could be the cause(s) of this error? Could it be due to a Surge server issue, DNS misconfiguration, or any other possibilities?
2. How can I resolve this issue? For example, is there a way to clear any potentially corrupted session data for Surge?

**Any guidance or resolution would be greatly appreciated!**

**Comment by afc163** [comment]
Same problem: https://github.com/ant-design/ant-design/actions/workflows/preview-deploy.yml

**Comment by uyarn** [comment]
Same problem today

**Comment by NguyenTaiAnh** [comment]
Same problem

**Comment by mulleydev** [comment]
I'm glad I'm not the only one.

**Comment by mulleydev** [comment]
Test founded on another issue :
```me@me:~$ mirrors=(sfo lhr yyz jfk ams fra sgp blr syd nrt)
for mirror in ${mirrors[@]}; do echo -n $mirror ' '; curl -H "Host: longing-ray.surge.sh" --write-out '%{http_code}\n' -o /dev/null --silent --connect-timeout 10 ${mirror}.surge.sh; done

sfo  504
lhr  200
yyz  504
jfk  504
ams  504
fra  504
sgp  504
blr  504
syd  504
nrt  504
```

**Comment by ahmed-lotfy-dev** [comment]
i've the same problm too and changed node verison and used every error fix on google and eventually  changed distro

**Comment by rafaismyname** [comment]
“same” wont solve anything….
but i dont work there and i need to deploy my changes!!!
SAME! 🙋‍♂️
@sintaxi please help

**Comment by sintaxi** [comment]
@hsulijen Appreciate the detailed report. Looking into it.

**Comment by sintaxi** [comment]
Initial issue appears to be resolved. You should not be able to publish.

Please let me know if you continue to have issues.

**Comment by hsulijen** [comment]
@sintaxi I've tried two of my projects, and they both worked. 
The issue seems to be resolved.
Thank you very much!

**Comment by sintaxi** [comment]
@hsulijen thanks for confirming!
