### ISSUE TITLE
Can't surge at all - error with publishing

### ISSUE THREAD

**Issue by cfjedimaster** [sintaxi/surge#55]
Whenever I do a surge test, I get: Aborted - you must be granted access to publish to quiet-creature.surge.sh

I haven't tried to set the domain at all - I'm taking the defaults.

**Comment by cfjedimaster** [comment]
Ok, so if I don't take the default and enter one, it seems to work (I assume I picked one someone else didn't). I thought the random domain was supposed to work? Also, what happens if I take google.com?

**Comment by cfjedimaster** [comment]
For my test, I used www.cajunipsum.com, which "worked", but I don't want to _really_ move my site yet, I'm just testing. I guess I can test w/ HOSTS. I'd rather use the random domain though from surge. Possible?

**Comment by kennethormandy** [comment]
I don’t think there is any checking to see if we have already used the randomly suggested domain, we assumed it would be so unlikely to collide, but maybe that’s not the case, thanks.

Do you mind trying:

```sh
surge --domain cajunipsum.surge.sh
```

…and letting me know if that works? Sorry for the trouble, thanks for checking it out!

**Comment by kennethormandy** [comment]
Actually—I can reproduce the issue now. Sorry, @cfjedimaster, looking into it and will report back. Thanks for documenting this.

**Comment by kennethormandy** [comment]
The random domain that gets suggested work properly now, @cfjedimaster. Sorry again for the trouble there and thanks to @sintaxi for the fix. Please let us know how it goes!

**Comment by onderweg** [comment]
I'm still experiencing this issue with a randomly selected domain.
E.g. `noiseless-leaf.surge.sh` , results in

```
Aborted - you must be granted access to publish to smakkelaarsveld.surge.sh
````

Works with my own domain though.

**Comment by sintaxi** [comment]
@onderweg this was resolved at 11:51am. which was moments before you filed this ticked. Do you mind trying again for me?

**Comment by cfjedimaster** [comment]
Confirmed it works for me.

**Comment by onderweg** [comment]
Yes, works for me as well :thumbsup:

**Comment by jasonmelgoza** [comment]
Caught this bug last night when trying Surge for the first time. Eveything is looking good now. :+1:

**Comment by kennethormandy** [comment]
Thanks everyone for your patience! You all definitely deserve some Surge stickers, if you want to sign up we’ll send them your way: https://surge.sh/stickers/

[![surge-avatar-350](https://cloud.githubusercontent.com/assets/1581276/6488750/77bf5ad6-c24e-11e4-83f2-91d5d89e4818.png)](https://surge.sh/stickers)

**Comment by louh** [comment]
Hey -- I just installed Surge tonight, and I'm getting this problem. Can't publish to any domain at all -- not the default one, not one I named, and not one I set in the `--domain` argument. I really wanted to try this out :-/

**Comment by tongrhj** [comment]
I'm having this issue too!

**Comment by sintaxi** [comment]
A security feature was activated when abuse was detected which prevented the creation of any new project. Issue is now resolved. Sorry for the inconvenience.

**Comment by louh** [comment]
Thanks so much! Bad timing, I guess.
Is there a way I can follow security/outage reports etc?

**Comment by dfahne** [comment]
I am having this problem now, with a custom domain. The old version is still up but I am not able to publish new changes.

**Comment by sintaxi** [comment]
@dfahne thanks for letting us know. Systems seem normal so not sure yet what problem you are running into. Feel free to email me directly at brock@surge.sh with more details and Ill dig further.

**Comment by rohyadav** [comment]
I'm having this issue. And i tried to logout and login but doesn't work for me can you please anyone help me out this.
before it was different login id that time worked but when i upload in different domain that got error.
but for now is there anyway to short it out this.

surge --domain imrohit.in

    Surge - surge.sh

              email: rohityadav.techie@gmail.com
              token: *****************
       project path: C:\workspaceArea\imrohit\
               size: 13 files, 64.6 KB
             domain: imrohit.in

    Aborted - you do not have permission to publish to imrohit.in

**Comment by eddycaldas** [comment]
Hi, 
I'm having the same problem:
Surge - surge.sh

              email: eddycaldas@live.com
              token: *****************
       project path: /Users/eddycaldas/jobs/
               size: 5 files, 5.1 KB
             domain: jobs.surge.sh

    Aborted - you do not have permission to publish to jobs.surge.sh

Please help... Thank you

**Comment by gone** [comment]
Can confirm, currently an issue

**Comment by pseuyi** [comment]
ran into this issue just now when when running `surge`. allowed me to create an account that i could login to but the randomly generated domain was clearly taken.

**Comment by seisenreich** [comment]
Same here.
Anything further we could provide you with to be able to fix this?

KR

**Comment by sintaxi** [comment]
It's unclear to me what problem this ticket represents? Id like to narrow this down into something that we can take action on since this ticket is really old but probably represents different problems for different people. Please chime in if you see this as one of these three problems or something else altogether...

1) subdomain collision when publishing a subdomain the CLI suggests?

2) Error thrown from fuzzy finder. https://github.com/sintaxi/surge/issues/392

3) Not having publish access due to changing surge accounts?

**Comment by seisenreich** [comment]
> It's unclear to me what problem this ticket represents? Id like to narrow this down into something that we can take action on since this ticket is really old but probably represents different problems for different people. Please chime in if you see this as one of these three problems or something else altogether...
> 
>     1. subdomain collision when publishing a subdomain the CLI suggests?
> 
>     2. Error thrown from fuzzy finder. #392
> 
>     3. Not having publish access due to changing surge accounts?

Hi Brock, thank you very much for taking your time.
And for answering so quickly.
If I understood it right, it should be number 1.

When I use `surge` in CLI - without using `--domain`- I get some random domain as result.
But this doman is already taken in many cases.

While that's no actual problem when using the domain CLI option, I think there could be a check for already taken random domains to improve the user experience of the tool.

An example:
```
surge

   Running as me (Student)

        project: /my/directory/to/publish
         domain: silky-range.surge.sh

   Aborted - you do not have permission to publish to silky-range.surge.sh
```
When I type that domain into my browser I find a web app uploaded to it.

Did this clarify what I mean? I have to admit that I've been in a hurry yesterday and should have given you more information.

Best Regards.

**Comment by lindsayloughlin** [comment]
I had the same issue when creating a new account, including multiple attempts in quick succession. **After waiting for around 60 seconds the authorisation and deployment were successful.** 

This may be due to the account creation happening in the background, possibly a consistency issue with account creation?

For brevity I was following through the Gatsby hello world example ( https://www.gatsbyjs.org/tutorial/part-one/ )

**Comment by n-lavrenko** [comment]
1. Try in the terminal (when you authorized in surge): 
`$ surge`
2. Then select a folder to upload: `/projects/johndoe/dist`
After that the progress were ran. 

```
Running as johndoe@gmail.com (Student)

        project: /projects/johndoe/public
        domain: somedomain.surge.sh
        upload: [===========         ] 55% eta: 42.7s (308 files, 150176416 bytes)
```

**Comment by MuhammadHammad999** [comment]
hello, whenever I try to surge, it says
Aborted - You to not have permission to publish ------

**Comment by junaidms111** [comment]
you do not have permission to publish to bootcamp_session2.surge.sh

**Comment by technikhil314** [comment]
Looks like it works if you wait for some time. Is there any rate limit on how fast can we publish???

**Comment by MuhammadHammad999** [comment]
It just requires changing the name.

**Comment by sintaxi** [comment]
@technikhil314 If you haven't verified your email you are FAR more likely to hit a rate limit.  Resetting your password will automatically verify your email if you think you may still need to do that that. If you still think you are being rate limited after doing that let me know and Ill take a closer look.

https://surge.sh/help/resetting-your-password.

**Comment by technikhil314** [comment]
@sintaxi Ok so creating account does not verify my email?? Is resetting the password the only way to verify email. The thing is I do not remember if I have reset my password. So I will give it a try. Will get back here if I face the same issue. Meanwhile let me know if you need any logs from my side if I face the issue. So that I wll immediately capture the logs before they get bloated by my ohter activities.

**Comment by psipher** [comment]
I had the same issue, since the path was public folder and i was running outside it,  while adding slash in the project caused this issue for me, however next time i let the default path and rather in the domain , i added /public and it worked.

**Comment by justingaylor** [comment]
I encountered this issue today with a new account created. I failed repeatedly until I verified by email (verification email received in my inbox). Then it worked like a charm. 🙇

**Comment by jitendravyas** [comment]
This is still a problem. Any solution yet?

**Comment by tornasvk** [comment]
> This is still a problem. Any solution yet?

remember to "Verify your email"

**Comment by nicovd737** [comment]
Having same issue even after verify my mail

**Comment by nicovd737** [comment]
Yes. after verify the mail, it works !

**Comment by faisalkhan215** [comment]
Hello, Friends
A lot of people have the issue of `#Aborted - you do not have permission to publish` to new users of surge but it is very simple that only you have to verify your email address thrugh which you created the account on the surge command line
Thanks

**Comment by h4ckdi** [comment]
I have verified email and still getting this error `#Aborted - you do not have permission to publish`

**Comment by faisalkhan215** [comment]
Hi @h4ckdi visit this link and go through the whole article step by step its a complete solution [How to use github actions with surge.sh](https://top3solution.com/2020/11/05/what-is-a-surge-sh-how-to-deploy-a-website-on-surge-sh-how-surge-sh-works-with-github-actions-how-to-deploy-static-webpage-to-surge-sh-with-github-actions/)

**Comment by paschalidi** [comment]
Had the same issue today. Installing the latest version solved it for me
```
npm uninstall -g surge
npm install -g surge
```

**Comment by broncha** [comment]
```
npx surge 
```
did it for me :)

**Comment by kevnoutsawo** [comment]
I had the same issue, I verified my email and it persisted. I then tried to put a very long and random name for the subdomain and it worked.
The user experience is unnecessarily frustrating, it should output a more precise message telling you that the subdomain is taken, not that you just don't have permission without saying why.

**Comment by EricoCartmanez** [comment]
For me it worked the 3d time executing the same command (`surge`)

**Comment by Kiddyshade** [comment]
Published to phobic-beam.surge.sh but can't see any of the index page there

**Comment by sintaxi** [comment]
@Kiddyshade The deployment worked, you don't have an `index.html` file in the root of your projects. Try visiting https://phobic-beam.surge.sh/gangweb.html or rename `gangweb.html` to `index.html` and redeploy.

I'm locking this ticket because too many people are getting notified when it's commented on.
