### ISSUE TITLE
Shut down domain

### ISSUE THREAD

**Issue by cfjedimaster** [sintaxi/surge#56]
The CLI should let me shut down (kill) a domain.

**Comment by sintaxi** [comment]
yes. agreed. will do.

**Comment by umbriel** [comment]
Question: how do you shut down domains at this time, if not though the CLI? 

Cheers

**Comment by cfjedimaster** [comment]
@umbriel is that for me? If so, it would depend on the platform. If an app server, I'd redirect to a static site. Or just kill the web server in general. A rare case for a 'real' site, but with Surge making it so easy to fire things up, I think being able to shut down is much more important.

**Comment by umbriel** [comment]
Sorry for hijacking the thread, it happened to be in context of my problem. (And yes I agree with you) I recently deployed a server onto a randomly generated url. It works as intended, but how do I now un-deploy said server so that I or anybody else cannot access the site?

**Comment by CITguy** [comment]
@umbriel: Currently, I would just replace the domain assets with a single `index.html` that displays that the domain is no longer in operation. However, that doesn't "kill" the domain. It just makes it unusable.

**Comment by sintaxi** [comment]
Stay tuned. I have a release on deck that has a teardown command.

**Comment by sintaxi** [comment]
All done. Just released `surge@0.8.0` which adds a `surge teardown` command. you can run it with or without an argument. If no argument is passed in it will check for a CNAME file and prompt you for confirmation or prompt you to enter a domain.

Let me know what you think.

**Comment by kennethormandy** [comment]
Here’s some additional help if you need it: [Tearing down a published project](http://surge.sh/help/tearing-down-a-project)

Now you’re ready to publish to a custom domain instead. ;) http://surge.sh/help/adding-a-custom-domain

**Comment by cfjedimaster** [comment]
Worked perfectly. Thanks. I didn't even have to cd to the dir - just did a list - saw the one I made while testing - and killed it. Excellent.
