### ISSUE TITLE
Assume current directory

### ISSUE THREAD

**Issue by cfjedimaster** [sintaxi/surge#57]
In the intro video, after setting a CNAME value, it looks like you did:

    surge

And the current directory was assumed. For me, when I do surge, it still prompts me for the folder. I have to do 

    surge .

to make it assume the current dir.

**Comment by kennethormandy** [comment]
That current directory should be assumed, yeah. Do you mind giving me some more details? Mind giving me your version of Surge, Node, and OS and I’ll try to reproduce? Thanks @cfjedimaster!

**Comment by cfjedimaster** [comment]
surge: 0.7.4
node: 0.10.36
os: osx Yosemite

**Comment by sintaxi** [comment]
@cfjedimaster good observation.

What I did there was pass in the directory I wanted to deploy so that I wouldn't get prompted (and have to hit enter). If I just typed `surge` it would still assume current working directory but would prompt me and give me in an opportunity to put in a different path. Make sense?

**Comment by cfjedimaster** [comment]
I thought in the video I saw you type *just* surge to redeploy (this was
after the initial setup).

On Wed, Mar 4, 2015 at 1:38 PM, Brock Whitten <notifications@github.com>
wrote:

> Closed #57 <https://github.com/sintaxi/surge/issues/57>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sintaxi/surge/issues/57#event-246257358>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by cfjedimaster** [comment]
Never mind- sorry - total brain fart.

On Wed, Mar 4, 2015 at 1:57 PM, Raymond Camden <raymondcamden@gmail.com>
wrote:

> I thought in the video I saw you type *just* surge to redeploy (this was
> after the initial setup).
>
> On Wed, Mar 4, 2015 at 1:38 PM, Brock Whitten <notifications@github.com>
> wrote:
>
>> Closed #57 <https://github.com/sintaxi/surge/issues/57>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sintaxi/surge/issues/57#event-246257358>.
>>
>
>
>
> --
> ===========================================================================
> Raymond Camden, Developer Advocate for MobileFirst at IBM
>
> Email : raymondcamden@gmail.com
> Blog : www.raymondcamden.com
> Twitter: raymondcamden
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
