### ISSUE TITLE
Brackets counted as part of the domain in terminal

### ISSUE THREAD

**Issue by kennethormandy** [sintaxi/surge#6]
In the following example:

```
       project path: (/Users/kennethormandy/Desktop/myproj)
               size: 4 files, 529 bytes
              email: kenneth@chloi.io
           password:
             domain: (picayune-vegetable.surge.sh)
```

Command+Clicking on the domain should open `http://picayune-vegetable.surge.sh/` but it opens `http://%28picayune-vegetable.surge.sh%29/` because of the brackets. Not sure if there’s a way to ignore that, or if we should just remove the `(` and `)` entirely.

**Comment by silentrob** [comment]
Removing the '(' is probably the easiest but this only applies for the pre-generated suggested domain. Working with your feedback yesterday perhaps making that field editable might be the right approach.

**Comment by kennethormandy** [comment]
Consensus was that this was resolved by explicitly listing the domain in the post flight (https://github.com/sintaxi/surge/commit/7d7ba6fbab0e259ef19c6b64d23e8293cbbb739c) so if you need to command click anything, it’s going to be that.
