### ISSUE TITLE
Ignoring files

### ISSUE THREAD

**Issue by onderweg** [sintaxi/surge#61]
I would like to have a way to ignore certain files when uploading a directory. For example OS X `.DS_store` files or files generated by my IDE.

**Comment by kennethormandy** [comment]
Hey, thanks for opening an issue! All dot files should be ignored by default, were you seeing any problems with this?

**Comment by sintaxi** [comment]
@onderweg you can create a `.surgeignore` file for that. Works just like a `.gitignore` file.

Also, if `.DS_Store`, or `.git` files are being moved that would be a bug. Surge is already set to ignore those.

**Comment by onderweg** [comment]
I saw `.DS_Store` popping up in "propagate on CDN: " line in the command line tool. But I don't know if this means the file was actually uploaded.

Anyway, a `.surgeignore` file sounds like a great solution!
