### ISSUE TITLE
naked/root domain and www subdomain

### ISSUE THREAD

**Issue by wihodges** [sintaxi/surge#64]
What's the best way to deal with serving example.com and www.example.com from same project?

Right now since I'm using grunt I just made two projects and deploy to both simultaneously.

**Comment by kennethormandy** [comment]
Hey, thanks for opening an issue!

One option is to, in your domain settings, add a `www` subdomain and 301 redirect it to `/`. (Or, vice versa: you can 301 redirect `/` to `www`). Then, just continue to deploy to the “official” one and the other should get redirected.

Let me know if that’s helpful.

**Comment by wihodges** [comment]
Ok thanks for input.

Yea the only thing I would suggest/want is if that were handled automatically then the Sugre.sh workflow would be even better. I love that unlike github or s3 all I have to do is add A record to domain and push. It's brilliant. Having to setup a redirect is extra steps.  

I wonder if its possible to have multiple entries in the CNAME file which all point to same project:
example.com
www.example.com
other.example.com

**Comment by kennethormandy** [comment]
Thanks for the feedback! We’ll keep this in mind and keep you posted. We definitely want to make that workflow as smooth as possible.

**Comment by onderweg** [comment]
Both the `www` version and the naked domain are working in my project.
The CNAME file only contains the naked domain name.

I'm not sure why it's working actually. Maybe because of the DNS setup at my hosting provider:

- CNAME `www` value is `@`
- A record value is `192.241.214.148` (surge IP)

**Comment by sintaxi** [comment]
I plan on tackling this issue very shortly.

@wihodges Well get this working automatically so there is no setup. FWIW - I don't think its good to serve the same content from multiple domains. I think we need a proper 301 redirect for best results.

What I think is the best solution here is to have `www.example.com` redirect to `example.com` if nothing exists at `www.example.com` but `example.com` does have something. The opposite could also be true.

Does that sound good to you folks?

**Comment by wihodges** [comment]
Awesome! @sintaxi  and I agree, with 'www' pointing to root domain.

**Comment by marvinroger** [comment]
Actually, just like [Github Pages](https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/) does:

* If your `CNAME` file contains `example.com`, then `www.example.com` will redirect to `example.com`.
* If your `CNAME` file contains `www.example.com`, then `example.com` will redirect to `www.example.com`.

**Comment by nicholasfc** [comment]
I'm using cloudflare and tried adding these DNS records to get a www working but with no luck.
- A record pointing to surge IP
- CNAME www with value of @ 

When I enter the www version of my domain I go to a surge error page. If you guys can add this option to work with both www and non-www I change from my current s3 bucket setup to surge in no time.

**Comment by sintaxi** [comment]
Auto redirects are now implemented. `www` redirects to non-www and visa-versa depending on which one you have published to. Let me know what you think.
