### ISSUE TITLE
Harp like basic auth 

### ISSUE THREAD

**Issue by glued** [sintaxi/surge#65]
Is there currently a way to do this with surge because this is a harp feature we use frequently.

**Comment by sintaxi** [comment]
Yep, just run `surge --build` in the root of a harp project and you will get the behaviour you expect. No need to compile locally.

**Comment by glued** [comment]
[tried it](http://smooth-fog.surge.sh/) but no luck... `harp.json` has `"basicAuth": [ "user:pass" ]` which prompts me locally but not deployed

**Comment by kennethormandy** [comment]
I was able to reproduce this with an `index.html` and a `_harp.json` file:

```json
{
  "basicAuth": "Ali Baba:Open, Sesame!"
}
```

Running it with Harp locally will require a password, but running `surge --build` and visiting the site won’t. I had this happen before the `--build` flag was added to Surge in v0.7.4 so I’m confident it is unrelated to that.

**Comment by sintaxi** [comment]
This is now resolved. no need to update surge. Just redeploy your the app.

**Comment by glued** [comment]
:+1:
