### ISSUE TITLE
Should be able to ignore files/folders from deployment

### ISSUE THREAD

**Issue by lewiscowper** [sintaxi/surge#74]
It'd be cool if surge could selectively not deploy things, with a .surgeignore file.

**Comment by sintaxi** [comment]
This is already implemented (exactly as you described it). Though not sure if windows compatible or not #73

**Comment by lewiscowper** [comment]
Ah, my bad. Is that documented somewhere?

**Comment by kennethormandy** [comment]
@lewiscowper Still working on that particular help page, sorry!

Surge already ignores `.` files, and you can expand on this list by creating a `.surgeignore` file. It works like a `.gitignore` file.

You can also use the `.surgeignore` for directories like with `.gitignore`. For example, if you wanted to ignore a directory called `psd/`, just add it:

```
psd/
```

Let us know how that works for you.

**Comment by lewiscowper** [comment]
Woo, that's awesome. :+1:
