### ISSUE TITLE
Ignoring _data.json to use no layout

### ISSUE THREAD

**Issue by jorgepedret** [sintaxi/surge#82]
There’s been a couple of cases where it doesn’t fully build my harp application, or something goes weird with the build and the site doesn’t render as expected. The second time, when I noticed, I have a page that I specified in my _data.json to not use layout, but it was using a layout. I had to redeploy to make it work properly.

It did it again. It seems to ignore the _data.json sometimes. Upgraded surge to 0.9, redeployed and the issue is gone, but I’m not sure if the upgrade fixed it.

Unfortunately, it continues to ignore _data.json in 0.9, even after deploying multiple times.

**Comment by sintaxi** [comment]
Hmm, I think the LRU cache in terrarform is caching that file. let me look into it.

**Comment by jorgepedret** [comment]
Thanks Brock. I was able to temporarily make it work by tearing it down and then deploying it again.

**Comment by kennethormandy** [comment]
Which version of Harp are you on, our of curiosity? The most reliable fix for now would probably be to compile locally and deploy the `www/` directory instead. I tend to make this a run script in my `package.json`, ex:

```js
"scripts": {
  "compile": "harp compile",
  "deploy": "npm run compile && surge ./www --domain typebrigade.com"
}
```

**Comment by jorgepedret** [comment]
Hey Kenneth, I'm on 0.15.2. That’s a good idea, I'll switch it later today.

**Comment by robmuh** [comment]
To follow on the build before surging idea a `.git/hooks/pre-commit` like this is very convenient:

```sh
#!/bin/sh

harp compile
[ $? -ne 0 ] && exit 1

surge www 
[ $? -ne 0 ] && exit 1
exit 0
```

You get the bonus of having a repo that is a few clicks from ready for [PhoneGap](http://build.phonegap.com) build as well (because of the committed `www`).

**Comment by kennethormandy** [comment]
Thanks @robmuh! We also put together a little example of how you could do this [using git hooks in your `package.json`](https://github.com/surge-sh/example-githooks). If you ever wanted to do a little write-up on your approach, we’d definitely share it out and link to it.

I’m going to close this issue now, since compiling locally first is definitely the approach we’d like to continue encouraging.
