### ISSUE TITLE
DNS (gandi.net) resolves but Surge.sh shows 'Page Not Found'

### ISSUE THREAD

**Issue by gyaresu** [sintaxi/surge#88]
### My static files: 
 * https://github.com/gyaresu/gareth.website

### Running the `surge.sh` command:
```
gyaresu@shazbot:~/programming/projects/gareth.website|master
⇒  surge .

              email: me@gareth.com.au
              token: *****************
       project path: /Users/gyaresu/programming/projects/gareth.website
               size: 3 files, 558 bytes
             domain: gareth.website
             upload: [====================] 100%, eta: 0.0s
   propagate on CDN: [====================] 100%
              users: me@gareth.com.au
         IP address: 192.241.214.148

    Success! Project is published and running at gareth.website

gyaresu@shazbot:~/programming/projects/gareth.website|master
```

### Gandi.net DNS: 
 * https://www.gandi.net/admin/domain/zone
```
@ 10800 IN A 192.241.214.148
* 10800 IN CNAME na-west1.surge.sh.
www 10800 IN CNAME na-west1.surge.sh.
```
### Result:
![screenshot 2015-04-16 15 02 39](https://cloud.githubusercontent.com/assets/29263/7192414/235126c8-e44a-11e4-9a8e-258eccb1bfe4.png)

Thanks! :cake:

**Comment by sintaxi** [comment]
The DNS appears to be working correctly.

You only have a README.md and CNAME file in your project so nothing is being displayed when you visit you site. Try adding an index.html file.

**Comment by gyaresu** [comment]
![screenshot 2015-04-16 15 19 50](https://cloud.githubusercontent.com/assets/29263/7192661/58f66dcc-e44c-11e4-9d84-563e00bbd22f.png)
@sintaxi 

while (true) :cake:

**Comment by sintaxi** [comment]
Far to say, we all have our moments :)
