### ISSUE TITLE
Support Access-Control-Allow-Origin: *

### ISSUE THREAD

**Issue by phated** [sintaxi/surge#91]
I just started playing with surge and it is awesome!

My use case is a paid set of SVG icons that I want to use with our new website (not static), but the icons can't be checked into the source due to the license.  I would like to host the icons on surge CDN and access them from my website but when I attempt to load with an ajax SVG loader, I am getting cross-origin errors.

What are your thoughts on supporting `Access-Control-Allow-Origin: *`?

**Comment by sintaxi** [comment]
I can dig it. How do you think the API should work?

**Comment by phated** [comment]
What would you think about having a file similar to CNAME but named CORS that has a list of newline-separated domains in it?  On the server-side, you could do something like http://stackoverflow.com/a/1850482

This would also easily allow `Access-Control-Allow-Origin: *` by just doing `echo "*" > CORS`

**Comment by sintaxi** [comment]
This is now implemented.

`echo "*" > CORS` works as expected.
