### ISSUE TITLE
Doesn't respect CNAME file

### ISSUE THREAD

**Issue by oskarrough** [sintaxi/surge#92]
Hi, I've added a CNAME file in my projects folder but it's not respected if I do `surge dist` e.g. add a destination. I'm on OS X.

**Comment by gyaresu** [comment]
@oskarrough What's the actual command you're using because I don't recognise `surge dist`

**Comment by oskarrough** [comment]
`surge dist` is the actual command I'm using? `dist` is the name of the folder I want to upload, relative to where I'm running the command. Which is the same place CNAME is.

Just `surge` works but I need my folder to be a subfolder (dist).

**Comment by sintaxi** [comment]
@oskarrough you can either put your CNAME in your `dist` directory or pass in your domain in the command line as your second argument. `surge dist example.com`.

If you wish to force SSL (redirect http to https) just deploy to `surge dist https://example.com`.

Let me know if you have any other issues.

**Comment by gyaresu** [comment]
Hey. Not a project owner but happy to try helping :)

Please dont't take this the wrong way but you haven't logged your commands or any errors. 

What's the exact contents of your `~/project/CNAME` file?

Can you run it explicitly by defining the project `-p` and domain `-d`. Then run it again without specifying the domain and post the log?

i.e.
```
⇒  mkdir certstuff
gyaresu@shazbot:~/programming/projects|
⇒  surge -p example -d example.surge.sh

              email: me@gareth.com.au
              token: *****************
       project path: /Users/gyaresu/programming/projects/example
               size: 0 files, 0 bytes
             domain: example.surge.sh
             upload: [====================] 100%, eta: 0.0s
   propagate on CDN: [====================] 100%
              users: me@gareth.com.au
         IP address: 192.241.214.148

    Success! Project is published and running at example.surge.sh
```

**Comment by oskarrough** [comment]
Thanks guys. Explicitly defining the domain and project using -p and -d or just `surge subfolder domain.com` works.

The confusion came form my initial thought that surge would honor any CNAME in the working directory, if the -p dir didn't contain any.

**Comment by kennethormandy** [comment]
Glad it’s sorted. Yeah, rather than check the working directory, we only check the deployment directory you pass in. So, one thing you can also do is copy the `CNAME` file into your `dist/` directory, often people make this a part of their build step (using Grunt/Gulp/npm or a static site generator).

Let us know if you have any other questions!

**Comment by j127** [comment]
Suggestion: the [docs](http://surge.sh/help/remembering-a-domain) aren't clear that `CNAME` should go in the directory that is getting pushed to surge. It sounds like `CNAME` should go at the root of the project and not in the deploy directory, but that doesn't seem to work.

> You can also save your domain to a CNAME file so you don’t have to type it into the CLI either. Add a CNAME file (no extension) to the root of the project you’re deploying, and Surge will use that automatically.

**Comment by sintaxi** [comment]
@j127 Thanks for reporting, I'll look into it. 

FWIW - I personally don't ever use a CNAME file. I prefer to just pass in the domain name `surge . example.com` or put it in package.json file...

```
{
  ...
  "scripts": {
    "deploy": "surge www example.com"
  }
}
```

In this case you would run `surge run deploy`.

**Comment by j127** [comment]
Thanks, it isn't actually for me, but I'll keep it in mind if I use it. I was helping someone deploy their site to Surge and it wasn't working, so I tested it and that seemed to be why the `CNAME` file wasn't being picked up.
