### ISSUE TITLE
Registration not possible on Windows 8.1 x64

### ISSUE THREAD

**Issue by brakmic** [sintaxi/surge#93]
I tried to deploy a simple project with just index.html in it but the registration procedure is not creating a proper logon for me. I entered my email and a password but surge keeps asking me to enter a password. I tried different combinations (with capital letters, special chars etc.). I also tried to use surge via Cygwin / Bash but still get the same "error".

**Comment by kennethormandy** [comment]
Hey, thanks and sorry for the trouble. Are you registered as an administrator account or do you have sufficient privileges on Windows? We’ve come across one error on Windows where it wasn’t possible to save your login due to that, we might not have accounted for every case yet.

I appreciate the details, I’ll try and reproduce it.

**Comment by brakmic** [comment]
I have admin privileges on Windows.

**Comment by kennethormandy** [comment]
Okay, thanks. And I forgot to ask before, do you mind letting me know exactly what version of Node, npm, and Surge you have too?

**Comment by brakmic** [comment]
Hi,

node v0.12.0
surge v0.11.1
npm v2.5.1

**Comment by glued** [comment]
one of my co-workers just tried to signup, same issue on windows 7 with node v0.12.0 and surge v0.11.1

**Comment by kennethormandy** [comment]
Hey, sorry for the delay on this. I spent a some more time trying to reproduce it, and as far as I can tell, it’s not a Windows-related problem. If you upgrade to the latest version of Surge, you’ll now get [a reset password message](https://surge.sh/help/resetting-your-password) after unsuccessfully entering your password three times. You can upgrade with:

```sh
npm install -g surge
```

[![](https://surge.sh/images/help/resetting-your-password.gif)](https://surge.sh/help/resetting-your-password)

We’re going to continue to work on the UI to make the messages clearer too. Thanks for opening this issue and feel free to re-open it if this doesn’t resolve it.

**Comment by kennethormandy** [comment]
Hey everyone,

Just to follow up on this issue, it actually was probably a Window-related after all. There was a problem for some people who were using the default command prompt. Really sorry about that!

Last week, we released v0.14.4 of Surge, which should fix the problem. You can install or update Surge with:

```sh
npm install --global surge
```

Please let me know how it goes! If you’d like, you can [read more about the update here](https://medium.com/@kennethormandy/257ab847aa0d).

**Comment by brakmic** [comment]
Hi,

Yes, it works!

Here's the proof :smiley: 

![surge](https://cloud.githubusercontent.com/assets/56779/9900449/305bcb90-5c61-11e5-8bef-7523ea11b125.png)

http://crooked-question.surge.sh/

Many, many thanks! :+1:
