### ISSUE TITLE
Certain images not deployed

### ISSUE THREAD

**Issue by sebastiangraz** [sintaxi/surge#95]
Sorry I've got a strange issue

Im running Surge v0.11.1 and Im getting a couple of '404 image not found' 

The strange part is that images from exactly the same directory are being loaded but __some__ of them are not. Is there a data limit on how many images I can load? Are the images corrupted (re-running surge and the same images are not found)?

Note: The images are display correctly on my local machine. 
Note 2: I just noticed some image names get capitalised on deployment.

**Comment by sintaxi** [comment]
Can you send to me the domain you deployed to, and what is a few examples of files that are missing?

**Comment by sebastiangraz** [comment]
http://giant-army.surge.sh/ - only some images are missing

**Comment by kennethormandy** [comment]
I think we might have resolved this in [the chat room](https://surge.sh/help/chat)? I’m going to close this issue, but if it’s still a problem, feel free to drop in there and ask, someone will be able to help get it sorted out. :)

**Comment by mhandie** [comment]
My images are not loading on surge

**Comment by mhandie** [comment]
I used an image for my background it’s not showing

**Comment by andrscyv** [comment]
I have this problem

**Comment by sintaxi** [comment]
@andrscyv Thanks for reporting your issue. Please understand that there is 60.8TB of data on surge.sh - which all seem to be working without issue. Commenting on this resolved issue notifies everyone else in this thread and this issue. So you should only do so if you think your input is relevant to them.  If you are having a problem I suggest [hopping in the slack channel](https://surge.sh/help/chat) or [opening a new ticket](https://github.com/sintaxi/surge/issues/new) and providing as much information as you can, including steps to reproduce the problem.
