### ISSUE TITLE
Adding groups of collaborators

### ISSUE THREAD

**Issue by alexlande** [sintaxi/surge#96]
Hey! Thanks for Surge, it's awesome.

It would be helpful if there was a way to add or remove groups of people as collaborators. Examples might be whitelisting everyone with a particular email domain, or everyone who's part of a certain GitHub org.

**Comment by kennethormandy** [comment]
Thanks Alex! I think you’ll like some of the things we’re working on then. I’ve sent you an email.

If anyone else stumbles across this and is interested, just get in touch: [kenneth@surge.sh](mailto:kenneth@shurge.sh)

**Comment by kennethormandy** [comment]
For others’ future reference, here’s how you can add [single or multiple collaborators](https://surge.sh/help/adding-collaborators) using their email.

If you’re interested in previewing an upcoming version of Surge that includes features specifically for teams, agencies, organisations, or similar, feel free to [send me an email](mailto:kenneth@surge.sh?subject=Surge for Teams) or join [our chat](https://surge.sh/help/chat).
